### ISSUE TITLE
Traceback on cell creation

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1018]
```
Traceback (most recent call last):
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/vtkcell.py", line 407, in event
    return qt_super(QVTKWidget, self).event(e)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_cell.py", line 100, in event
    for cell in self.getSelectedCellWidgets():
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/vtkcell.py", line 871, in getSelectedCellWidgets
    if not ren: ren = self.getActiveRenderer(self.iren)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/vtkcell.py", line 829, in getActiveRenderer
    epos = list(iren.GetEventPosition())
AttributeError: 'NoneType' object has no attribute 'GetEventPosition'
```

**Comment by aashish24** [comment]
This I will double check.. this is something directly related.
