### ISSUE TITLE
cdscan issue - invalid time coords

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1045]
The behavior when encountering problematic time coords seems to have changed with recent tweaks to cdscan (#949):

```
[durack1@crunchy ~]$ /usr/local/uvcdat/2014-10-02/bin/cdscan -x cmip5.HadGEM2-ES.piControl.r1i1p1.mo.atm.Amon.hus.ver-v20130114.latestX.xml.2014-10-02 /cmip5_css02/scratch/cmip5/output1/MOHC/HadGEM2-ES/piControl/mon/atmos/Amon/r1i1p1/v20130114/hus/*.nc
Finding common directory ...
Common directory: /cmip5_css02/scratch/cmip5/output1/MOHC/HadGEM2-ES/piControl/mon/atmos/Amon/r1i1p1/v20130114/hus/
Scanning files ...
/cmip5_css02/scratch/cmip5/output1/MOHC/HadGEM2-ES/piControl/mon/atmos/Amon/r1i1p1/v20130114/hus/hus_Amon_HadGEM2-ES_piControl_r1i1p1_185912-188411.nc
Setting reference time units to days since 1859-12-01
...
Warning, file hus_Amon_HadGEM2-ES_piControl_r1i1p1_217312-219811.nc, dimension time contains values in file hus_Amon_HadGEM2-ES_piControl_r1i1p1_185912-188411.nc
Traceback (most recent call last):
  File "/usr/local/uvcdat/2014-10-02/bin/cdscan", line 1657, in <module>
    main(sys.argv)
  File "/usr/local/uvcdat/2014-10-02/bin/cdscan", line 1364, in main
    combineKeys(timeproj, timedict, timeIsLinear, referenceDelta)
  File "/usr/local/uvcdat/2014-10-02/bin/cdscan", line 316, in combineKeys
    raise RuntimeError, 'Dimension %s in files %s [len(%s)=%d], %s [len(%s)=%d], is inconsistent'%(name, prevpath, name, (jind-iind+1), path, name, len(values))
RuntimeError: Dimension time in files hus_Amon_HadGEM2-ES_piControl_r1i1p1_217312-219811.nc [len(time)=1], hus_Amon_HadGEM2-ES_piControl_r1i1p1_185912-188411.nc [len(time)=300], is inconsistent

[durack1@crunchy ~]$ /usr/local/uvcdat/2015-02-10/bin/cdscan -x cmip5.HadGEM2-ES.piControl.r1i1p1.mo.atm.Amon.hus.ver-v20130114.latestX.xml.2015-02-10 /cmip5_css02/scratch/cmip5/output1/MOHC/HadGEM2-ES/piControl/mon/atmos/Amon/r1i1p1/v20130114/hus/*.nc
Finding common directory ...
Common directory: /cmip5_css02/scratch/cmip5/output1/MOHC/HadGEM2-ES/piControl/mon/atmos/Amon/r1i1p1/v20130114/hus/
Scanning files ...
/cmip5_css02/scratch/cmip5/output1/MOHC/HadGEM2-ES/piControl/mon/atmos/Amon/r1i1p1/v20130114/hus/hus_Amon_HadGEM2-ES_piControl_r1i1p1_185912-188411.nc
Setting reference time units to days since 1859-12-01
...
/cmip5_css02/scratch/cmip5/output1/MOHC/HadGEM2-ES/piControl/mon/atmos/Amon/r1i1p1/v20130114/hus/hus_Amon_HadGEM2-ES_piControl_r1i1p1_217312-219811.nc
Setting reference time units to days since 1859-12-01
Traceback (most recent call last):
  File "/usr/local/uvcdat/latest/bin/cdscan", line 1677, in <module>
    main(sys.argv)
  File "/usr/local/uvcdat/latest/bin/cdscan", line 1163, in main
    sepname = disambig(var.id, vardict, var.size, compareVarDictValues, (tempdomain, None))
  File "/usr/local/uvcdat/latest/bin/cdscan", line 425, in disambig
    uniqname = '%s_%d'%(name,num)
TypeError: %d format: a number is required, not instancemethod
```
@painter1 do you have any insights to add here?

**Comment by doutriaux1** [comment]
@painter1 is that the issue you are fixing right now?

**Comment by doutriaux1** [comment]
@durack1 the first error seems to be due to bad files, is that correct?

**Comment by painter1** [comment]
I'm looking at this right now.  I think it's unrelated to another thing which I fixed recently.

**Comment by durack1** [comment]
@doutriaux1 @painter1 yep this is definitely bad files (badly defined time coord), but it would be better for cdscan to gracefully exit (with a warning/error code) than to bomb like it is..

**Comment by durack1** [comment]
@painter1 as discussed the last time the cmip5 xml script was run out of 147877 files which were attempted to be written just 37 were likely candidates for cdscan failing without reporting a warning/error message..

Next time I revisit these issues I'll outline a number of test cases and their behaviors and document these in a new issue.

**Comment by painter1** [comment]
I created a pull request for a change which will fix this bug (and another).   There's no new error checking, but a little bug fix will restore the previous behavior, i.e.

RuntimeError: Dimension time in files hus_Amon_HadGEM2-ES_piControl_r1i1p1_217312-219811.nc [len(time)=1], hus_Amon_HadGEM2-ES_piControl_r1i1p1_214812-217311.nc [len(time)=300], is inconsistent

**Comment by durack1** [comment]
Great thanks @painter1 I'll keep an eye on this when it's back into master and running through the cmip5 xml creation..

**Comment by doutriaux1** [comment]
@painter1 let's not closed before merging :wink: but I merged now so we're good.
