### ISSUE TITLE
AttributeError: 'QCDATWidget' object has no attribute 'inputPorts'

### ISSUE THREAD

**Issue by dlonie** [UV-CDAT/uvcdat#1046]
There is UVCDAT GUI problem that looks like a unexpected widget is being placed into a spreadsheet:

    Traceback (most recent call last):
      File "/ssd/src/uvcdat-build/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 963, in dropEvent
        self.sheet.selectCell(row, col, False)
      File "/ssd/src/uvcdat-build/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_sheet.py", line 507, in selectCell
        self.setActiveCell(row, col)
      File "/ssd/src/uvcdat-build/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_sheet.py", line 517, in setActiveCell
        toolBar = self.parent().getCellToolBar(row, col)
      File "/ssd/src/uvcdat-build/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 252, in getCellToolBar
        container.toolBar = toolBarType(self)
      File "/ssd/src/uvcdat-build/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_cell.py", line 326, in __init__
        self.createToolBar()
      File "/ssd/src/uvcdat-build/install/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1559, in createToolBar
        if cell.inputPorts[0][0].var.var.rank()>2:
    AttributeError: 'QCDATWidget' object has no attribute 'inputPorts'

To reproduce, create a default boxfill from on the clt sample data.

(Note, you may need to workaround issue #1017 in order to reproduce. The diff below is a hacky workaround that just lets the VisTrail parser finish).

    --- vistrails/packages/vtk/init.py
    +++ vistrails/packages/vtk/init.py
    @@ -158,6 +158,8 @@ def get_method_signature(method, docum='', name=''):
     
         """
         doc = method.__doc__ if docum=='' else docum
    +    if not doc:
    +        return []
         tmptmp = doc.split('\n')
         tmp = []
         for l in tmptmp:

**Comment by dlonie** [comment]
Oops, this is a duplicate of #1019.
