### ISSUE TITLE
Cython classmethod_utility_code used in VisTrails vtDVD3D

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcdat#1056]
The old Cython had a module classmethod_utility_code referenced by VisTrails vtDVD3D/InteractiveConfiguration.py.  The new Cython doesn't have it (at least, not in the same place) but the module is still imported by InteractiveConfiguration.py.  It seems not to be needed, but I don't know because this code is unfamiliar to me.

This issue causes an ImportError exception when you build a new UV-CDAT and try to run the GUI.

**Comment by doutriaux1** [comment]
@painter1 can you post the error here please.

**Comment by painter1** [comment]
painter1@caradoc:[uvcmetrics]:[63615]> uvcdat --output=""
WARNING: UVCDAT setup already sourced for this install location.
WARNING: You shouldn't source setup_runtime anymore.
['Adelon', 'Arabic', 'AvantGarde', 'Chinese', 'Clarendon', 'Courier', 'Greek', 'Hebrew', 'Helvetica', 'Maths1', 'Maths2', 'Maths3', 'Maths4', 'Russian', 'Times', 'default']
Uncaught exception on initialization: ImportError: cannot import name classmethod_utility_code
Traceback (most recent call last):
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/uvcdat.py", line 89, in <module>
    v = gui.application.start_application()
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/application.py", line 703, in start_application
    x = VistrailsApplication.init(optionsDict)
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/application.py", line 160, in init
    self.createWindows()
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/application.py", line 554, in createWindows
    self.uvcdatWindow = UVCDATMainWindow()
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/mainwindow.py", line 74, in __init__
    self.createDockWindows()
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/mainwindow.py", line 140, in createDockWindows
    self.varProp = VariableProperties(self)
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/variable.py", line 116, in __init__
    self.createOpenDAPTab()
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/variable.py", line 293, in createOpenDAPTab
    from packages.vtDV3D.RemoteDataBrowser import RemoteDataBrowser
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/packages/vtDV3D/__init__.py", line 68, in <module>
    from packages.vtDV3D.CDMS_DatasetReaders import *
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/packages/vtDV3D/CDMS_DatasetReaders.py", line 11, in <module>
    from packages.vtDV3D.InteractiveConfiguration import *
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/packages/vtDV3D/InteractiveConfiguration.py", line 23, in <module>
    from Cython.Compiler.Symtab import classmethod_utility_code
ImportError: cannot import name classmethod_utility_code

**Comment by doutriaux1** [comment]
@vvpalav if you can figure out this one quickly it would be awesome, if you think it's going to take too long, let's just revert to the older Cython.

**Comment by painter1** [comment]
I think you just can delete the offending import line.  I just hope that someone who knows what the code is about can do it.

**Comment by doutriaux1** [comment]
@painter1 yes that's why I assigned @vvpalav he can tell us rapidly I'm sure.

**Comment by ThomasMaxwell** [comment]
I don't know where this line of code came from, but when I ran into this error I deleted the offending line and it did not seem to cause any problems with DV3D.

-- Tom

**Comment by remram44** [comment]
I just ran into that. I don't see why this should completely crash the GUI, either. I'm supposed to work on the new UV-CDAT GUI but I keep stumbling on unrelated, app-breaking bugs.

**Comment by doutriaux1** [comment]
https://github.com/UV-CDAT/VisTrails/pull/14 fixes this
