### ISSUE TITLE
No usch text combined

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcdat#1096]
When I use the GUI to make a diagnostics plot it looks good - until I move the mouse over it.  Then something raises the following exception:

Exception: No usch text combined: __texttable_733759201101579:::__textorientation_833871807321088
Traceback (most recent call last):
  File "/Users/painter1/bin/uvcdat-2015.03.02/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/configurator.py", line 269, in hover
    obj = self.in_display_plot(point, display)
  File "/Users/painter1/bin/uvcdat-2015.03.02/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/configurator.py", line 384, in in_display_plot
    tc = vcs.gettextcombined(dp.g_name)
  File "/Users/painter1/bin/uvcdat-2015.03.02/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/manageElements.py", line 1613, in gettextcombined
    raise Exception,"No usch text combined: %s:::%s" % (Tt_name_src,To_name_src)

Thereafter, if I click on another unrelated window (e.g. for a shell) the plots disappear.

**Comment by painter1** [comment]
This is with a new UV-CDAT built less than an hour ago, off a pull of UV-CDAT master and VisTrails uvcdat-master, and a pull of the metrics dvel branch.

**Comment by painter1** [comment]
After I redrew the plots, they wouldn't disappear any more.

**Comment by doutriaux1** [comment]
@chaosphere2112 could it be linked to configurator?

**Comment by chaosphere2112** [comment]
@doutriaux1 Looks like it definitely is; @painter1, how about I swing by and you show me how to reproduce?

**Comment by chaosphere2112** [comment]
Just submitted a pull request to fix this issue, should get merged soon.

**Comment by chaosphere2112** [comment]
Should be fixed in latest master.
