### ISSUE TITLE
Saving an animation at 4 frames per second on mac creates green animation

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1118]
When I save an animation of CLT at 4 FPS on my mac, it outputs a solid green video. I've tried this both from my UI stuff as well as from scripts.

@doutriaux1

**Comment by chaosphere2112** [comment]
We tried this on Ubuntu and it worked perfectly fine, so there's probably something askew in my computer's setup. @doutriaux1, here's the FFMPEG log:

```
ffmpeg version 0.11.1 Copyright (c) 2000-2012 the FFmpeg developers
  built on Feb 26 2015 10:47:33 with clang 5.1 (clang-503.0.40)
  configuration: --extra-cxxflags=/Users/fries2/build/build/FFMPEG --enable-shared --enable-zlib --prefix=/Users/fries2/uvcdat/Externals
  libavutil      51. 54.100 / 51. 54.100
  libavcodec     54. 23.100 / 54. 23.100
  libavformat    54.  6.100 / 54.  6.100
  libavdevice    54.  0.100 / 54.  0.100
  libavfilter     2. 77.100 /  2. 77.100
  libswscale      2.  1.100 /  2.  1.100
  libswresample   0. 15.100 /  0. 15.100
[image2 @ 0x7f9708806600] max_analyze_duration 5000000 reached at 5000000
Input #0, image2, from '/Users/fries2/.uvcdat/e0e56a3c9fdc7033a9761441552b3aec1a0ccf77/anim_%d.png':
  Duration: 00:00:30.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgb24, 814x606, 4 fps, 4 tbr, 4 tbn, 4 tbc
[buffer @ 0x7f970840dc60] w:814 h:606 pixfmt:rgb24 tb:1/4 sar:0/1 sws_param:flags=2
[buffersink @ 0x7f970840df60] No opaque field provided
[format @ 0x7f970840e260] auto-inserting filter 'auto-inserted scaler 0' between the filter 'src' and the filter 'format'
[scale @ 0x7f970840e600] w:814 h:606 fmt:rgb24 sar:0/1 -> w:814 h:606 fmt:yuv420p sar:0/1 flags:0x4
Output #0, mp4, to '/Users/fries2/Desktop/anim.mp4':
  Metadata:
    encoder         : Lavf54.6.100
    Stream #0:0: Video: mpeg4 ( [0][0][0] / 0x0020), yuv420p, 814x606, q=2-31, 1024 kb/s, 4 tbn, 4 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png -> mpeg4)
Press [q] to stop, [?] for help
frame=  120 fps=0.0 q=14.3 Lsize=    3832kB time=00:00:30.00 bitrate=1046.5kbits/s    
video:3831kB audio:0kB global headers:0kB muxing overhead 0.035101%

**Comment by doutriaux1** [comment]
@chaosphere2112 can you point me to a script so I can use exact same data on my mac and ubunutu and see if i can reproduce this. Also did you try to preserve the png (option in x.close()) and see what they look like? You could send me these pngs and we can try to run ffmpeg on them on various system

**Comment by chaosphere2112** [comment]
```
import vcs, cdms2, sys

x = vcs.init()
clt_file = cdms2.open(sys.prefix + "/sample_data/clt.nc")
clt = clt_file["clt"]
x.plot(clt, bg=1)
x.animate.create()
x.animate.save("green.mp4", rate=4)
x.close()
```

This does it for me.

What’s the option to preserve the pngs? I watched as they were created, and they all looked fine. I can’t seem to see anything that would preserve them.

**Comment by doutriaux1** [comment]
```
x.close(preserve_pngs = True)
```

**Comment by chaosphere2112** [comment]
```
Traceback (most recent call last):
  File "/Users/fries2/Desktop/green.py", line 9, in <module>
    x.close(preserve_pngs = True)
  File "/Users/fries2/uvcdat/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 3864, in close
    a = self.backend.close(*args,**kargs)
TypeError: close() got an unexpected keyword argument 'preserve_pngs'
```

**Comment by doutriaux1** [comment]
Interesting... ok will fix that. I worked at one point...

**Comment by doutriaux1** [comment]
sorry it is:
```
x.animate.close(preserve_pngs = True)
```

**Comment by chaosphere2112** [comment]
OK, I’ve got a directory of PNGs… I tried printing out the command from the ffmpeg function, and it looks like this:

ffmpeg -y  -r 4 -i /Users/fries2/.uvcdat/98ffd71bb38c8c339cc7eaa4b6eaf03f621ebcdb/anim_%d.png -r 4  -b:v 1024k  green.mp4

Which doesn’t work– complains about anim_%d not being a file

**Comment by chaosphere2112** [comment]
I've got most of this sorted out in a branch, but it's not quite working yet. Will finish after Chico trip.
