### ISSUE TITLE
UVCDAT on Hopper

### ISSUE THREAD

**Issue by HarinarayanKrishnan** [UV-CDAT/uvcdat#1149]
I am trying to build and install the latest version of uvcdat on Hopper. Unfortunately, I am running into several issues. Which tag should I be using? (2.1.0 or uvcdat-2.1.0)?

I get a blank screen. (see attachment). Also, new VTK OpenGL windows keep popping up, but they are blank as well.  
The ASD options in taylor diagram are gone. Only default remains, this crashes uvcdat when Michael tries to run.

![screenshot from 2015-03-16 16 41 25](https://cloud.githubusercontent.com/assets/1823999/6678910/ebbf2d90-cbfd-11e4-937b-db8e22edceb5.png)

**Comment by doutriaux1** [comment]
@HarinarayanKrishnan please use what is in master, or better wait a couple of days and use our pre-2.2 tag.
To see all the output/errors tr
```
uvcdat --output=""
```

also try removing your ${HOME}/.uvcdat
```
rm -rf ${HOME}/.uvcdat
```

**Comment by HarinarayanKrishnan** [comment]
Tried both. Output below

Is there a flag to build against VTK with OSMesa? Or do I rebuild manually? Additional VTK windows pop up.

-----
['Adelon', 'Arabic', 'AvantGarde', 'Chinese', 'Clarendon', 'Courier', 'Greek', 'Hebrew', 'Helvetica', 'Maths1', 'Maths2', 'Maths3', 'Maths4', 'Russian', 'Times', 'default']
/usr/common/graphics/uvcdat/uvcdat-build/install/lib/python2.7/site-packages/vcs/utils.py:594: UserWarning: unable to source file: /usr/common/graphics/uvcdat/uvcdat-build/install/share/uvcmetrics.jsoni [Errno 2] No such file or directory: '/usr/common/graphics/uvcdat/uvcdat-build/install/share/uvcmetrics.json'
  warnings.warn("unable to source file: %si %s" % (script,err))
PVClimate plots not loaded.
Error when loading package_config_file: /global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/core/uvcdat/plots/PVClimate/registry.cfg No module named paraview.simple
Traceback (most recent call last):
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/core/uvcdat/plotmanager.py", line 105, in load_plots
    helper = self.parse_helper_type_str(pkg_parser.get(p, 'helper'))
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/core/uvcdat/plotmanager.py", line 80, in parse_helper_type_str
    module = __import__(path, globals(), locals(), [klass_name])
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/pvclimate/pvclimate_pipeline_helper.py", line 25, in <module>
    from pvgenericcell import *
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/pvclimate/pvgenericcell.py", line 12, in <module>
    import paraview.simple as pvsp
ImportError: No module named paraview.simple
   ------ Loaded plot Histogram, varnum = 1 ------ 
None None

create plot functions:  [('graphicsMethodName', ['default']), ('plotOrder', ['1']), ('boxfill_type', ['linear']), ('color_1', [16]), ('color_2', [239]), ('datawc_calendar', [135441]), ('datawc_timeunits', ['days since 2000']), ('datawc_x1', [1e+20]), ('datawc_x2', [1e+20]), ('datawc_y1', [1e+20]), ('datawc_y2', [1e+20]), ('levels', [[1e+20, 1e+20]]), ('ext_1', [False]), ('ext_2', [False]), ('fillareacolors', [None]), ('fillareaindices', [None]), ('fillareastyle', ['solid']), ('legend', [None]), ('level_1', [1e+20]), ('level_2', [1e+20]), ('missing', [1]), ('projection', ['linear']), ('xaxisconvert', ['linear']), ('xmtics1', ['']), ('xmtics2', ['']), ('xticlabels1', ['*']), ('xticlabels2', ['*']), ('yaxisconvert', ['linear']), ('ymtics1', ['']), ('ymtics2', ['']), ('yticlabels1', ['*']), ('yticlabels2', ['*'])]
Traceback (most recent call last):
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/core/modules/vistrails_module.py", line 327, in update
    self.compute()
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1282, in compute
    self.cellWidget = self.displayAndWait(QCDATWidget, input_ports)
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/spreadsheet/basic_widgets.py", line 247, in displayAndWait
    return spreadsheetWindow.displayCellEvent(e)
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_window.py", line 491, in displayCellEvent
    sheet.setCellByType(row, col, e.cellType, e.inputPorts)
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 320, in setCellByType
    newCell.updateContents(inputPorts)
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1352, in updateContents
    self.createCanvas()
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1327, in createCanvas
    self.canvas = vcs.init(backend=self.GetRenderWindow())
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/vtk/vtkcell.py", line 316, in GetRenderWindow
    self.SetRenderWindow(win)
  File "/global/common/hopper_cle52/graphics/uvcdat/uvcdat-build/install/vistrails/vistrails/packages/vtk/vtkcell.py", line 360, in SetRenderWindow
    self.mRenWin.SetDisplayId(vp)
TypeError: SetDisplayId argument 1: value is _bd15d0_p_void, required type is void_p

**Comment by doutriaux1** [comment]
@HarinarayanKrishnan to build against MESA use
```
-DCDAT_BUILD_OFFSCREEN=ON
````
but you obviously lose the GUI if you do so.

**Comment by aashish24** [comment]
@HarinarayanKrishnan CDAT_BUILD_OFFSCREEN won't be useful to you. The problem we had earlier was realted to the fact the render window was linked with Qt rendering system. This issue should be fixed in the current master.

**Comment by durack1** [comment]
@HarinarayanKrishnan is this issue resolved?

**Comment by HarinarayanKrishnan** [comment]
I am waiting for the next release. I would consider the matter closed for
now.

Best regards,
Hari
