### ISSUE TITLE
Taylor diagrams (plot set 14)

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1180]
From AMWG diagnostics in the gui I get the following error

Traceback (most recent call last):
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 660, in buttonClicked
    self.applyClicked()
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 777, in applyClicked
    self.displayCell(res30, row, col)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 856, in displayCell
    G = V[Gtype]
KeyError: 'Taylor'

**Comment by aashish24** [comment]
what version of UV-CDAT you are using?

**Comment by mcenerney1** [comment]
The latest; built on 3/25

**Comment by aashish24** [comment]
just from a default check point of view, can you review your .uvcdat folder? It should be in your home directory. 

- Aashish

**Comment by mcenerney1** [comment]
What would I be looking for?

**Comment by aashish24** [comment]
sorry remove (and not review)

remove .uvcdat folder

**Comment by mcenerney1** [comment]
No change

**Comment by aashish24** [comment]
It is a bug then. I have added the labels. We will try to fix it asap.

**Comment by aashish24** [comment]
@painter1 @isubsmith  any ideas?

**Comment by doutriaux1** [comment]
Probably expects "taylor" lower case but it's just a wild guess

**Comment by doutriaux1** [comment]
Also this does not belong here this is uvcmetrics code in visyrails code.... please report where appropriate...

**Comment by isubsmith** [comment]
No idea, but I think Charles' guess is likely along the right path. 

I suspect V['Taylor'] in this context doesn't exist. Someone probably needs to find out what types exist for a projectController.plot_manager._plot_list["VCS"] and adjust accordingly. 


         pm = projectController.plot_manager
         V=pm._plot_list["VCS"]
         gm = res30.presentation
         from packages.uvcdat_cdms.init import get_canvas, get_gm_attributes, original_gm_attributes
         from gui.uvcdat.uvcdatCommons import gmInfos
         Gtype = res30.type
         G = V[Gtype]  <- barfs

**Comment by doutriaux1** [comment]
very close from having a solution

**Comment by durack1** [comment]
@aashish24 @doutriaux1 should this be a `2.4` milestone? I think it's a very strong candidate..

**Comment by aashish24** [comment]
@durack1 agreed. @doutriaux1 are you looking into this?

**Comment by mcenerney1** [comment]
No it should not be considered for 2.4.This issue has not been looked at for several months. At the time noone was calling for this capability and it was pushed down in priority. It is folly to drop everything else to get this operational for this release. It should be considered for the next release.

**Comment by durack1** [comment]
@mcenerney1 was the issue that taylor diagrams (and the functionality to create them) was no longer working? If so this is a high priority, as the taylor diagram functionality is a big deal for scientists using `vcs`

**Comment by doutriaux1** [comment]
I would say let's not try to fix it here and let's have @chaosphere2112 revisit it with the new GUI.

**Comment by durack1** [comment]
@doutriaux1 @aashish24 I just noted that this bug was [noted as `critical` in the `v2.2.0` release notes](https://github.com/UV-CDAT/uvcdat/wiki/UV-CDAT-2.2-Change-Log#critical) so might warrant fixing if it's possible in the `2.4.0` timeline?

**Comment by doutriaux1** [comment]
it's GUI related, the taylordiagrams work from command line as far as I know. I'm pretty sure it's not going to be touched for 2.4 and @chaosphere2112 touched up GUI revisit will take care of this.

**Comment by durack1** [comment]
@doutriaux1 might be a good idea to rename this issue then - I'm uncertain what it is, but from the current title thought it indicated that taylor diagrams are currently not working

**Comment by doutriaux1** [comment]
@chaosphere2112 assigned this to you, just so that we make sure it works in the next GUI.
