### ISSUE TITLE
PlotProperties getting QPromptCellWidget instead of cell widget

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1181]
From UV-CDAT/VisTrails#30

It seems that `PlotProperties` is updated from `ProjectController#update_workflow()` just after `execute_plot()` and this is not safe. The `PlotProperties` gets the `QPromptCellWidget` instead of the new cell widget.

A workaround can be added for 2.2 but this should definitely be fixed later.

**Comment by doutriaux1** [comment]
@remram44 actually the work around doesn't really work when I apply it (https://github.com/UV-CDAT/VisTrails/pull/30) it does not break anymore, but doesn't seem to produce any plot any longer. @vvpalav or @hgohil2805 can you take a look please?

**Comment by hgohil2805** [comment]
@remram44 This is caused by the cell not being deleted correctly and because of the changes  that we made last week of setting it to none in the delete later method. I had encountered similar exception with the changes that I had shown you before and I had used a catch all which worked fine (not sure if you remember the changes).  

Until we find the the object which is keeping the reference to the cell and remove it while deleting, I feel keeping a catch all should be fine as incorrect cell removal should probably be the only thing which causes the exception to be thrown .

**Comment by doutriaux1** [comment]
@hgohil2805 not sure the catch all is actually working in this case, it does prevent it form failing, but nothing gets drawn in the spreadsheet. Now that might be something else that prevents the plot from appearing I'm not positive.

**Comment by remram44** [comment]
@hgohil2805 I have no idea what you're talking about and disagree on all points.

**Comment by remram44** [comment]
@doutriaux1 I don't run into the issue, with either workaround or none at all. What system are you using?

The patch in UV-CDAT/VisTrails#30 should prevent the traceback you gave from happening; it might interfere with the the PlotProperties, but really can't prevent plotting.

**Comment by doutriaux1** [comment]
It's very hard to reproduce. Has to come from diagnostics and taor diagrmasn. Ask @mcenerney1 or @painter1 for steps and location of data. Because I can't reproduce with uvcmetrics test data. I need @mcenerney1 special data.

**Comment by mcenerney1** [comment]
I really need help on this one and I'll help out in any way possible. On aims1 in my area (mcenerney1) there are two files cam35_data.tar (model data) and taylor_obs_data.tar (observation data).  You'll need to download them to reproduce the issue.  Documentation on running the AMWG diagnostics from the  gui can be found at http://uvcdat-dev.llnl.gov/documentation/diagnostics/diagnostics.html
To run from the command line, you'll need uvcmetrics. In the directory uvcmetrics/src/python/frontend run  
    diags.py  --model path=$HOME/uvcmetrics_test_data/cam35_data/,climos=yes \
    --obs path=$HOME/uvcmetrics_test_data/obs_data/,filter='f_startswith("NCEP")',climos=yes \
    --outputdir $HOME/Documents/Climatology/ClimateData/diagout/ --package AMWG --sets 14 \
    --seasons JAN --plots yes --vars T --varopts '200 mbar'

Once again I'll do whatever it takes to get this resolved; email, phone calls, telepathy. Thanks
Jim

**Comment by doutriaux1** [comment]
@mcenerney1 they need instructions for gui I fixed command line already. @painter1 merged it.
But gui needs my uvcdat pretty merged in and them your instructions so they can see the failure.

**Comment by doutriaux1** [comment]
Again we don't know if the failure prevents plot or if something else in diagnosticsWidgets.py prevents it once we are pas the failure

**Comment by mcenerney1** [comment]
To see the failure do the following. Assuming the data directories are in cam35_data and taylor_obs_data, bring up uvcdat. Under Diagnostics select AMWG. A new window comes up. Under Use Dataset 1, click Set Path and choose the cam35_data directory. Next select Use Observations 1. Set Path to taylor_obs_data. Make sure NCEP apears in the adjoining window.  If not, select it in the menu.  In the upper window that displays the complete list of diagnostics,  select 14 - Taylor diagrams. Once done there is a section just below to set the variable options. In the Variables pull down menu, select T. In the seasons menu, select JAN.  In the Variables Options menu, select "200 mbar". Now click Apply and off it goes. If you run into a snag, let me know.

**Comment by mcenerney1** [comment]
Any progress on this issue? Are the instructions clear?

**Comment by hgohil2805** [comment]
I'll try and reproduce the error right now. Will let you know if I find any solution or have any issues reproducing it.

**Comment by mcenerney1** [comment]
Thanks!

**Comment by hgohil2805** [comment]
can you give us the download link for the data files?. I found this but I am not sure if this is the correct link
http://www.cgd.ucar.edu/cms/rneale/tools/amwg_mean_diagnostics.html

**Comment by mcenerney1** [comment]
I have 2 tar files, cam35_data and taylor_obs_data, in mcenerney1 on aims1.llnl.gov
Do you have an account?

**Comment by painter1** [comment]
If you have no account on aims1, what about rhea.ccs.ornl.gov or any other ORNL machine with Lustre mounted?

**Comment by hgohil2805** [comment]
Nope, I don't have an account on any of them.

**Comment by painter1** [comment]
NERSC, Argonne, any place other than NYU?

**Comment by hgohil2805** [comment]
No.
You guys are going to have to upload them someplace .

**Comment by mcenerney1** [comment]
Can you get me an account at NYU?

**Comment by painter1** [comment]
Jim, I think you can upload to ftp.llnl.gov and Hardick can download from there.

**Comment by hgohil2805** [comment]
Nah, I don't think I can get you an NYU account :(

**Comment by mcenerney1** [comment]
Jeff found a way to get you the files (Thanks!). We have a ftp site, here's how to get the files
ftp ftp.llnl.gov
username = anonymous
password = your email
Once you're login
cd outgoing/mcenerney1
There are 2 files: cam35_data.tar and taylor_obs_data.tar
get cam35_data.tar  
and the same of taylor_obs_data.tar

**Comment by hgohil2805** [comment]
Thank you guys..
I have the files. I have 12 .nc files in cam_35_data and around 15-16 files in taylor_obs_data. I am unable to load the dataset. As soon as I select the cam_35 directory, it pops up the following error. I figured thought something might be wrong with my build so I tried to use the same data files on a completely fresh build that I have on another VMware Ubuntu but it pops up the same error. 

Here's the screen shot 

![error](https://cloud.githubusercontent.com/assets/9386084/7029011/fdb17c02-dd0e-11e4-9b9e-2a80eca8abf8.jpg)

Am I doing something wrong? If not, do you get the same error?

**Comment by hgohil2805** [comment]
Sorry, I meant to ask if you get the error when you use the GUI..

**Comment by mcenerney1** [comment]
Jeff
Is this the wrong version of uvcmetrics in uvcdat is the wrong version?

**Comment by painter1** [comment]
Hardik,  haven't seen that.   It surprises me.  If self.opts is initialized as an Options object (options.py), then self.opts._opts==[] initially.  And it is initialized as an Options object, see the beginning of the class definition of DiagnosticsDockWidget.

Jim, if you're asking whether this is about incompatible versions, I'd say you're probably right.  At least, it must be some kind of a build issue.

**Comment by mcenerney1** [comment]
I believe the solution is to get the latest uvcmetrics and build with it.

**Comment by hgohil2805** [comment]
Jim, wouldn't that only help when you are running it from the command line?

**Comment by painter1** [comment]
No, the GUI file diagnosticsDocWidget.py is just an interface to the diagnostics in uvcmetrics.  In particular, options.py was changed a month or two ago.  If you have the latest VisTrails (uvcdat-master), it requires a recent version of options.py.

**Comment by mcenerney1** [comment]
Thanks, Jeff. I think I've seen this before.

**Comment by hgohil2805** [comment]
Ah ok, 
let us know if it works with the latest uvcmetrics.

**Comment by painter1** [comment]
You won't see your error message with the latest ucmetrics.  Most things work.  I think we're back to the original VisTrails issue here.

**Comment by mcenerney1** [comment]
Hardik, can I do anything more to help you??

**Comment by hgohil2805** [comment]
Jim, I am not sure what exactly the latest uvcmetrics will help you with. Will it help remove only the error that I have attached above on the screen shot or will it actually help you plot things correctly?

Jeff, I built the new uvcdat about 15 days ago using the files that were considered a good fit for 2.2. Should it not have the latest options.py file?

**Comment by mcenerney1** [comment]
I think the version in uvcdat has a problem.  The latest will only remove the error on your screen shot.

**Comment by painter1** [comment]
The UV-CDAT distribution often comes with months-old copies of the diagnostics, aka metrics.  I routinely wipe out the metrics installation there and install my own.   In fact, that was necessary when I built a new UV-CDAT on March 25, about the same time as yours.  So I'm sure that you need to delete whatever UV-CDAT has put into site-packages/metrics, and then go to the uvcmetrics source tree (devel branch) and type "python setup.py install".  It's quick and easy.

**Comment by hgohil2805** [comment]
Ok, Thanks Jim.

Jeff. I am going to try and install the new one. Will let you know if I face any issues. 
Also, I feel that if this is something that you normally always do and considering that we do require it to make sure that all the features correctly, then we need to work on some way to  make sure that the latest distribution has the latest versions (if it is not already included).

**Comment by doutriaux1** [comment]
@painter1 it is also worth noting that you guys are NOT using "master" but "devel" branch.

**Comment by painter1** [comment]
The *release* versions of UV-CDAT do contain appropriate versions of the diagnostics - at least, they have so far.   Probably development versions of UV-CDAT contain obsolete versions of the diagnostics because that dates to the previous release.

**Comment by mcenerney1** [comment]
Hardik
Were you able to get past the uvcmetrics issues?

**Comment by hgohil2805** [comment]
Jim,
I wasn't able to.

Jeff, Can you tell me where exactly I need to issue the python setup.py install command from?

**Comment by hgohil2805** [comment]
Jim,
The traceback given here by charles is the one you see right?https://github.com/UV-CDAT/VisTrails/pull/30

I can use that in the meanwhile to see if I can find something.

**Comment by painter1** [comment]
Hardik,
For running "python setup.py install", there are two things you need to get right:
1. The right python:  First install UV-CDAT.  Then run its setup_runtime.sh or setup_runtime.csh.
2. The right setup.py:  cd to the root of the uvcmetrics directory tree.  That has a file setup.py.  Then run "python setup.py install".

And it is safer if, before running setup.py, you find the python's site-packages directory, and delete the contents of its metrics subdirectory.

**Comment by mcenerney1** [comment]
I believe this is an issue. There may be others.

**Comment by hgohil2805** [comment]
I believe this is the one? https://github.com/UV-CDAT/uvcmetrics/blob/master/setup.py

So because I had removed my build directory and I could not the file anywhere, I got the files from https://github.com/UV-CDAT/uvcmetrics and then ran setup.py , after removing the files from site-packages/metrics which put new files in its place . This however still gave me the same error that I had from the screen shot. 

You think building entire uvcdat from master will help?

**Comment by painter1** [comment]
Do not use the master branch of uvcmetrics.  Use the devel branch.  Make sure that you do a pull from the uvcmetrics project repository, devel branch.  I don't have your directory structure, so I can't tell for sure what you're doing.  Anyway, there's only one setup.py in uvcmetrics.

**Comment by painter1** [comment]
Here's where to pull from: git@github.com:UV-CDAT/uvcmetrics.git
And do a "git checkout devel".   In uvcmetrics the master branch is rarely updated, usually at the same time as a UV-CDAT release.

**Comment by hgohil2805** [comment]
Ok, will try that out.

**Comment by mcenerney1** [comment]
Hardik
Any luck with this issue?

**Comment by hgohil2805** [comment]
Nope, not yet. I've got the new uvcmetrics (thanks you!) and I can load the files. Can you give me a data set that works correctly so that I can look at how the flow works.?

**Comment by mcenerney1** [comment]
The data cam35_data.tar and taylor_obs_data.tar should work. Found on ftp ftp.llnl.gov

**Comment by hgohil2805** [comment]
Ok I'll give it a run.

**Comment by hgohil2805** [comment]
Guys,
New issue. So this is what happens when I load obs_data (Observation 1). I don't think this is because of the local changes that I might have made. 
![cam_load_error](https://cloud.githubusercontent.com/assets/9386084/7122446/77e70238-e1e9-11e4-8f42-3da1bcbcb0ba.jpg)

**Comment by painter1** [comment]
This does look like a bug, but it is totally unrelated.
1. You are using the same path for "Dataset 1" and "Observations 1".  They are supposed to be different.  The whole point of all this is to compare two different sets of data.
2. You are testing plot set 2.  This issue is about plot set 14, Taylor diagrams.

**Comment by painter1** [comment]
To expand on what I just wrote:  The GUI was used incorrectly.  It is a bug because there shouldn't be an exception in this case.  But fixing that bug will not contribute to fixing this issue, #1181.
Hardik, you need to test with a real observation data set under "Observations 1", e.g. the NCEP ANN data.  This must be in a different directory from the one which has model data, cam35_data in this case.  You also need to test plot set 14, Taylor diagrams.  The other plot sets are not relevant to this issue.

**Comment by hgohil2805** [comment]
Jeff, I took the wrong print screen (I did do the same required things before but then tried to continue doing things anyways to test ).

 Here's the one after selecting the correct things. 
![new_error](https://cloud.githubusercontent.com/assets/9386084/7122857/23f22d6c-e1ec-11e4-9371-fbc475900ccd.jpg)

**Comment by painter1** [comment]
Under your obs path is a pulldown menu "Obs set 1".    Can you choose anything there?  My guess is that there's no data in your obs path.  But whatever the reason, there is supposed to be a default obs set in the pulldown menu; and if there are more possibilities you should see them if you click on it.

**Comment by hgohil2805** [comment]
No the drop down menu is unusable before as well as after after the error pops up. Don't know if that's related.

In the obs_data directory, I have 16 .nc files. Is there something specific that you'd like me to check?

**Comment by painter1** [comment]
Please list the files in obs_data, and tell me what versions you have for options.py and diagnosticsDockWidget.py.  Make sure that you have actually installed the ones you think you have.
Put print statements in Options.__init__() (options.py) near the end of the medthod, and prepareObs1 (diagnosticsDockWidget.py) before the line which raises the exception.  Print out the values of self._opts['obs'] and self.opts['obs'] respectively.  Install these changes and run again.  Then please tell me what got printed out.

**Comment by hgohil2805** [comment]
ok, So I think we should just try and move on to fixing the actual problem of the cell widgets here. Jeff or Jim, can you post a  stack trace of what you get after you load everything correctly and the error pops up?.

I'll talk to Remi and we'll try to fix the actual problem and hopefully that should help plot things correctly too.

**Comment by hgohil2805** [comment]
Ok I'll do those things and let you know. Here are the files that I have in the obs_data directory
![files](https://cloud.githubusercontent.com/assets/9386084/7123847/04abec70-e1f3-11e4-86d0-d6d60b6687af.jpg)

**Comment by painter1** [comment]
Thanks.   Actually the only one you need is NCEP_ANN_climo.nc, because you're testing with the ANN season.  The others are for other seasons.  The xml.orig file is harmless garbage.
Something's seriously wrong, because you have the data and the system isn't seeing it.  I suspect that you are still seeing an issue with incompatible versions of the diagnostics and VisTrails - or something else, it's hard to guess from here.  Adding print statements will at least ensure that you are running what you think you're running.

**Comment by hgohil2805** [comment]
Ok I am not sure if it is diagnostics. Because I used to get the error pop up as soon as I tried to load the cam data before but now cam loads fine but it's obs which is causing the issue. Let's check with the prints.

**Comment by hgohil2805** [comment]
Prints out an empty list for options.init() 

```file - options.py, value of self._opts['obs'] is =  []```

and prints out 

```File - diagnosticsWidget, value of self.opts['obs'] is  = [{'filter': None, 'path': '/home/iceman/testdata/obs_data'}] ```

for prepareObs1

**Comment by painter1** [comment]
Hardik, Copy NCEP_ANN_climo.nc to SPAM_ANN_climo.nc.  I think we may have a bug where the system expects there to be more than one obs set available.

**Comment by mcenerney1** [comment]
Here's a the output 

Traceback (most recent call last):
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 661, in buttonClicked
    self.applyClicked()
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 783, in applyClicked
    self.displayCell(RES30, row, col, dropInfo=(plot_number == 0))
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 853, in displayCell
    projectController.variable_was_dropped(varDropInfo)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/project_controller.py", line 779, in plot_was_dropped
    self.check_update_cell(sheetName,row,col, update)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/project_controller.py", line 913, in check_update_cell
    self.update_cell(sheetName, row, col, reuse_workflow)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/project_controller.py", line 995, in update_cell
    reuse_workflow)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/project_controller.py", line 1042, in update_workflow
    self.update_plot_configure(sheetName, row, column)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/project_controller.py", line 849, in update_plot_configure
    widget = self.get_plot_configuration(sheetName,row,col)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/project_controller.py", line 907, in get_plot_configuration
    cell.plots)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 76, in show_configuration_widget
    return CDMSPlotWidget(controller,version,plots,vars)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1112, in __init__
    self.create_plot_widget()
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1237, in create_plot_widget
    stacked_widget = self.create_conf_widgets()
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1278, in create_conf_widgets
    self.add_conf_widget(plot_module)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1285, in add_conf_widget
    show_buttons=False)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/packages/uvcdat_cdms/widgets.py", line 37, in __init__
    self.gmEditor = self.createEditor(self, self.gmName)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/packages/uvcdat_cdms/widgets.py", line 82, in createEditor
    return QTaylorDiagramEditor(self.tabWidget, gmName)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/graphicsMethodsWidgets.py", line 830, in __init__
    self.initValues(self.gm)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/graphicsMethodsWidgets.py", line 867, in initValues
    self.markersTab.initValues(gm)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/graphicsMethodsWidgets.py", line 988, in initValues
    s = self.getGMMarkerAttributeValue(M,"status",i)
  File "/usr/local/uvcdat/03_25_15/vistrails/vistrails/gui/uvcdat/graphicsMethodsWidgets.py", line 1081, in getGMMarkerAttributeValue
    return v[i]
IndexError: list index out of range

**Comment by mcenerney1** [comment]
Hardik
I could call you and walk through the diagnostics if that would help.
What's a good phone number?
Jim

**Comment by hgohil2805** [comment]
Hi Jim,
I wasn't in at work yesterday so couldn't reply. I am trying what jeff had suggested, will let you know if it works. If not, give me a call at +1-917-717-6588

**Comment by mcenerney1** [comment]
Good! Let me know. I have a meeting at 9 am(PT).

**Comment by hgohil2805** [comment]
I was able to load both the files now but now it shows two new errors. Here's the first one,


```
File "/home/iceman/uvcdat-latest/15-03-24/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 364, in build_plot_pipeline_action
    ops2, new_conns, pm = CDMSPipelineHelper.create_actions_from_plot_obj( controller, var_modules, cell_module, plot, added_vars, i+1 )
  File "/home/iceman/uvcdat-latest/15-03-24/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 311, in create_actions_from_plot_obj
    plot_functions.append((attr,[pickle.dumps(getattr(initial_values,attr))]))
  File "/home/iceman/uvcdat-latest/15-03-24/lib/python2.7/copy_reg.py", line 77, in _reduce_ex
    raise TypeError("a class that defines __slots__ without "
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled

```

So I changed the pickling to the binary protocol in pipeline_helper.py, .

```
-plot_functions.append((attr,[pickle.dumps(getattr(initial_values,attr))))
+plot_functions.append((attr,[pickle.dumps(getattr(initial_values,attr)),-1]))

```
But now it shows the following error. It could be because of the change from Ascii to Binary pickling . I am looking into this.  
```
Traceback (most recent call last):
  File "/home/iceman/uvcdat-latest/15-03-24/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 661, in buttonClicked
    self.applyClicked()
  File "/home/iceman/uvcdat-latest/15-03-24/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 743, in applyClicked
    self.plot_spec = self.ds_menu[diagnostic](model, obs, variable, season, self.region_box, aux)
  File "/home/iceman/uvcdat-latest/15-03-24/lib/python2.7/site-packages/metrics/packages/amwg/amwg.py", line 2705, in __init__
    self.plan_computation( model, obs, varid, seasonid, aux )
  File "/home/iceman/uvcdat-latest/15-03-24/lib/python2.7/site-packages/metrics/packages/amwg/amwg.py", line 2791, in plan_computation
    L = FN.split('/')
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by mcenerney1** [comment]
I think this would result from either a bad specification of either the model data or obs data.

**Comment by hgohil2805** [comment]
Hey Jim, Can you call me? I have a couple of questions.

**Comment by mcenerney1** [comment]
I got your answering machine. I'm here 925-422-1963 or I'll call again.

**Comment by hgohil2805** [comment]
```

UV-CDAT Diagnostics, command-line version
file - options.py, value of self._opts['obs'] is =  []
Added set:  {'climos': 'yes', 'end': None, 'name': None, 'filter': None, 'start': None, 'path': '/home/iceman/uvcmetrics_test_data/cam35_data/', 'type': 'model'}
Added set:  {'climos': 'yes', 'end': None, 'name': None, 'filter': 'f_startswith("NCEP")', 'start': None, 'path': '/home/iceman/uvcmetrics_test_data/obs_data/', 'type': 'obs'}
Enabling NetCDF compression on output files
ERROR, output directory /home/iceman/Documents/Climatology/ClimateData/diagout/ does not exist!

```

**Comment by painter1** [comment]
Try creating the directory yourself.

**Comment by hgohil2805** [comment]
Works.. !
![taylor](https://cloud.githubusercontent.com/assets/9386084/7166844/903f3404-e37e-11e4-8904-283291c6e63d.jpg)

**Comment by doutriaux1** [comment]
Hardik,

I fixed the pickle issue your vcs must not be up to date.

C.

**Comment by mcenerney1** [comment]
Good you can get the graphic from the command line.  you even have the missing x axis as I do.

**Comment by mcenerney1** [comment]
Hardik
It's been quite a while since we talked about this one.  Now that uvcdat is released we should resurrect this issue.  I just tried it again from the gui and get the same error as on April 13, above. Any thoughts on what's going on?  I'm available to help on this!!
Jim

**Comment by hgohil2805** [comment]
Jim,
Yes we should try to get this working. I am currently working on GUI testing but I'll look into this too.

**Comment by mcenerney1** [comment]
Hardik
Some new info on this issue.  I spent yesterday afternoon in the debugger trying to isolate the issue and could not find it.  However, for some reason uvcdat does not crash as before. Now it simply runs but produces no graphics.  I don't know what changed but this may help you.
Jim

**Comment by remram44** [comment]
What changed is probably UV-CDAT/VisTrails#30

**Comment by doutriaux1** [comment]
as @remram44 mentioned in https://github.com/UV-CDAT/VisTrails/pull/30 it needs a "real" fix. But nobody seemed to have found time for it...

**Comment by hgohil2805** [comment]
Jim, I thought that you were using the latest build with that fix in it. I am going to try and solve the  cell and the plot properties problem, hopefully that helps to generate the plot correctly too.

**Comment by mcenerney1** [comment]
I was using a build with all of the updates. I just rebuilt from the new release (just to be sure) and it behaves the same: it doesn't crash but it proceeds normally and there is no graphic.

**Comment by aashish24** [comment]
@mcenerney1 are we going to fix this in 2.4?

**Comment by doutriaux1** [comment]
@chaosphere2112 can you take a look, I'd say if it takes more than 2 minutes, let's wait for the new GUI.

**Comment by chaosphere2112** [comment]
@doutriaux1 Yup, I'll poke at it.

**Comment by chaosphere2112** [comment]
@doutriaux1 OK, definitely going to take more than a couple of minutes. I'm gonna vote we wait for the new GUI on this one.

**Comment by doutriaux1** [comment]
moved to 3.0
