### ISSUE TITLE
Some standard vcs methods don't work (as expected) on a dv3d canvas

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#1188]
Note that everything I report is based on the stock 2.1.0 UV-CDAT, so some things may have already been corrected

**x** below is a dv3d canvas

Can you save images from an dv3d canvas the way you do it with a regular vcs canvas?
* **x.png('test')** produces a black image. But maybe it's due to a problem with GL or my window manager
* **x.pdf('test')** produces an image that's very incomplete, compared to what I have in the canvas

* I have already pointed out in #1187 that **x.close()** prints *Closing!* but does not close the window
```
>>> x.close()
Closing!
```

* **x.clear()** does not seem to clear the dv3d canvas (I still have the image and the dv3d buttons/sliders). But dv3d is aware that there is nothing left to plot, because I get 2 different exceptions when calling x.png() and x.pdf(). It would probably be nicer to have a single and more informative exception message like *Can't save an image from an empty Canvas*?
```
>>> x.png('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/Canvas.py", line 4730, in png
    return self.backend.png(file,width,height,units,draw_white_background, **args )
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/VTKPlots.py", line 1371, in png
    raise Exception,"Nothing to dump aborting"
Exception: Nothing to dump aborting

>>> x.pdf('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/Canvas.py", line 4770, in pdf
    return self.backend.pdf(file,W,H)
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/VTKPlots.py", line 1360, in pdf
    return self.vectorGraphics("pdf", file, width, height, units)
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/VTKPlots.py", line 1331, in vectorGraphics
    raise Exception("Nothing on Canvas to dump to file")
Exception: Nothing on Canvas to dump to file
```

**Comment by chaosphere2112** [comment]
@jypeter I had noticed that x.clear() doesn't work currently. There's a specific exception that skips over the 3D plots in the clear function right now; @ThomasMaxwell is there a good way to destroy a DV3D app short of exiting the program? I didn't see anything in my cursory glance around.

**Comment by ThomasMaxwell** [comment]
UVCDAT used to build cleanly on our viz cluster.   After doing a pull from the master branch yesterday I’m now getting the following SciPy build error.   Has SciPy been changed?


[ 70%] Performing configure step for 'SCIPY'

CMake Error at /usr/local/uvcdat-test/build/SCIPY-prefix/src/SCIPY-stamp/SCIPY-configure.cmake:56 (message):

  CTEST_FULL_OUTPUT


   Command failed: 1

   '/usr/local/scratch/tpmaxwel/cmake/bin/cmake' '-DCONFIG_TYPE=.' '-DCDAT_USE_SYSTEM_LAPACK:STRING=OFF' '-DLAPACK_LIBRARIES:STRING=/usr/lib64/liblapack.so' '/usr/lib64/libblas.so' '-DBLAS_LIBRARIES:STRING=/usr/lib64/libblas.so' '-P' '/usr/local/uvcdat-test/build/CMake/SCIPY_configure_step.cmake'

   From /usr/local/uvcdat-test/build/SCIPY-prefix/src/SCIPY-stamp/SCIPY-configure-out.log


  -------------------------------------------------


  Processing scipy/cluster/_hierarchy.pyx


  Cythonizing sources


  -------------------------------------------------


   From /usr/local/uvcdat-test/build/SCIPY-prefix/src/SCIPY-stamp/SCIPY-configure-err.log


  -------------------------------------------------


  Configuring SCIPY:


  /usr/local/uvcdat-test/build/build/SCIPY





  Error compiling Cython file:


  ------------------------------------------------------------


  ...


      Mark node i as visited.

      """

      bitset[i >> 3] |= 1 << (i & 7)








  cpdef calculate_cluster_sizes(double[:, :] Z, double[:] cs, int n):


                                      ^


  ------------------------------------------------------------





  scipy/cluster/_hierarchy.pyx:47:37: Expected an identifier or literal


  Traceback (most recent call last):


    File "/usr/local/uvcdat-test/build/build/SCIPY/tools/cythonize.py", line 198, in <module>

      main()

    File "/usr/local/uvcdat-test/build/build/SCIPY/tools/cythonize.py", line 194, in main

      find_process_files(root_dir)

    File "/usr/local/uvcdat-test/build/build/SCIPY/tools/cythonize.py", line 186, in find_process_files

      process(cur_dir, fromfile, tofile, function, hash_db)

    File "/usr/local/uvcdat-test/build/build/SCIPY/tools/cythonize.py", line 160, in process

      processor_function(fromfile, tofile)

    File "/usr/local/uvcdat-test/build/build/SCIPY/tools/cythonize.py", line 71, in process_pyx

      raise Exception('Cython failed')


  Exception: Cython failed


  Traceback (most recent call last):


    File "setup.py", line 253, in <module>

      setup_package()

    File "setup.py", line 246, in setup_package

      generate_cython()

    File "setup.py", line 164, in generate_cython

      raise RuntimeError("Running cythonize failed!")


  RuntimeError: Running cythonize failed!


  CMake Error at

  /usr/local/uvcdat-test/build/CMake/SCIPY_configure_step.cmake:58 (message):


    Error in config of SCIPY








  -------------------------------------------------




make[2]: *** [SCIPY-prefix/src/SCIPY-stamp/SCIPY-configure] Error 1

make[1]: *** [CMakeFiles/SCIPY.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

**Comment by chaosphere2112** [comment]
... not that I know of. Paging @aashish24

**Comment by ThomasMaxwell** [comment]
The DV3DPlot.quit() method destroys the plot but I think it does not currently close the window.

**Comment by doutriaux1** [comment]
Yes Rémi couldn't build on his mac without it.

**Comment by chaosphere2112** [comment]
@doutriaux1 ... Are you on the right issue here?
