### ISSUE TITLE
color map failure on special plot

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1220]
When I make a hofmuller plot (see attached video) and I try to change the color map.. the plot fails and I get an error.

https://www.dropbox.com/s/xtlbzhc9x2lipo8/huffmuller_fail_color_map.mov?dl=0

**Comment by doutriaux1** [comment]
@potter2 it is very difficult to read the error at the end of the video. Next time do you mind copy/pasting it in here? thanks.

**Comment by potter2** [comment]
here
Traceback (most recent call last):
File "/Users/potter/uvcdat/build-uvcdat/install/vistrails/vistrails/gui/uvcdat/colormapEditorWidget.py", line 327, in applyChanges
self.activeCanvas.setcolormap(str(self.colormap.currentText()))
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 5421, in setcolormap
self.update()
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 1041, in update
return self.backend.update(*args,**kargs)
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VTKPlots.py", line 333, in update
self.configureEvent(None,None)
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VTKPlots.py", line 231, in configureEvent
self.canvas.plot(*pargs, render = False, **key_args[i])
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 2613, in plot
a = self.__plot( arglist, keyargs )
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 3387, in __plot
copy_mthd=vcs.creategraphicsmethod(arglist[3],arglist[4])
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/utils.py", line 1514, in creategraphicsmethod
copy_mthd=func(source = name)
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/manageElements.py", line 402, in createisofill
return isofill.Gfi(name, source)
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/isofill.py", line 529, in __init__
setattr(self,att,getattr(src,att))
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/isofill.py", line 465, in _setdatawc_y1
value2=VCS_validation_functions.checkDatawc(self,'datawc_y1',value)
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VCS_validation_functions.py", line 784, in checkDatawc
value = value.torel(self.datawc_timeunits,self.datawc_calendar).value, 1
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/isofill.py", line 335, in _gettimeunits
return self._datawc_timeunits
AttributeError: _datawc_timeunits



Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

On Apr 17, 2015, at 11:05 AM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@potter2<https://github.com/potter2> it is very difficult to read the error at the end of the video. Next time do you mind copy/pasting it in here? thanks.

**Comment by doutriaux1** [comment]
thanks @potter2 ! that helps a lot! Will fix today.

**Comment by vvpalav** [comment]
#1214 .. Referenced

**Comment by doutriaux1** [comment]
@potter2 just tried it on "clt.nc" and works for me, following script works as well, can you please try again. Thanks
```
import vcs,os,cdms2

f=cdms2.open(os.path.join(vcs.prefix,"sample_data","clt.nc"))
s=f("clt",latitude=slice(25,26),squeeze=1)

x=vcs.init()
q=x.getisofill("quick")
x.plot(s,q)
raw_input("press enter")
x.setcolormap("bl_to_darkred")
raw_input("press enter")
```

**Comment by doutriaux1** [comment]
@potter2 confirmed it works again.
