### ISSUE TITLE
Error while plotting meshfill plot

### ISSUE THREAD

**Issue by vvpalav** [UV-CDAT/uvcdat#1284]
Exception is caught while plotting mesh fill plot. Entire application crashes after this.

```
Traceback (most recent call last):
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/core/modules/vistrails_module.py", line 327, in update
    self.compute()
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1276, in compute
    self.cellWidget = self.displayAndWait(QCDATWidget, input_ports)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/spreadsheet/basic_widgets.py", line 247, in displayAndWait
    return spreadsheetWindow.displayCellEvent(e)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/spreadsheet/spreadsheet_window.py", line 490, in displayCellEvent
    sheet.setCellByType(row, col, e.cellType, e.inputPorts)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 320, in setCellByType
    newCell.updateContents(inputPorts)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1450, in updateContents
    self.canvas.plot(cgm,*args,**kwargs)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 2617, in plot
    a = self.__plot( arglist, keyargs )
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 2730, in __plot
    arglist[1]=MV2.array(g.getMesh())
UnboundLocalError: local variable 'g' referenced before assignment
```

GUI:

![screen shot 2015-05-05 at 11 43 42 pm](https://cloud.githubusercontent.com/assets/6840965/7487201/e52fb396-f380-11e4-9f14-780ab864d578.png)

**Comment by remram44** [comment]
No, I don't see this error

![resized_taskmngr-launcher1](https://cloud.githubusercontent.com/assets/426784/7495878/ae7908d0-f3de-11e4-8c39-7cf95ca799f3.png)

**Comment by vvpalav** [comment]
Just tried again, same exception. FYI - I have a fresh build of UVCDAT from master.
@aashish24 @doutriaux1 can you please try this one.

**Comment by remram44** [comment]
You built the wrong branch, `release` has the fix (#1247)

**Comment by vvpalav** [comment]
:+1: .. I built from master

**Comment by doutriaux1** [comment]
@aashish24 we should really merge release PR into master as well.

**Comment by remram44** [comment]
Release branches are usually merged into development... Git really intends for 'master' to be the latest.

**Comment by doutriaux1** [comment]
I agree.

**Comment by doutriaux1** [comment]
@aashish24 should I go "dirty" and merge release into master? Or do you (or anyone else) want to take the time to do this cleanly.

**Comment by remram44** [comment]
If you do, there'll be exactly no difference between release and master... I don't know why there are two branches to begin with.

**Comment by doutriaux1** [comment]
things are going to go into master soon that shouldn't go into release.
