### ISSUE TITLE
scalar FileVariable as data for createVariable()

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcdat#1325]
Suppose you have a scalar FileVariable fv, i.e. fv.shape==().  You want to create a scalar TransientVariable from it, so you call cdms2.createVariable( fv ).  It throws an exception!  The reason is that TransientVariable.__init__() calls data.subSlice() as almost the first thing it does, and assumes that the result is a TransientVariable with a getDomain() method.  It isn't, subSlice() on a scalar FileVariable is a numpy scalar (numpy.int32 in my case) and hence has no such method.

My workaround is to supply as data fv.subSlice() rather than fv.  But this is a bug - either in TransientVariable.__init__() or in FileVariable.subSlice(), your choice (or my choice if I'm the one to fix it).

**Comment by ThomasMaxwell** [comment]
While you’re fixing this one could you please make TransientVariables pickable?   They currently throw a number of exceptions if you try to pickle/unpickle them.   Being able to pickle these objects would greatly facilitate the parallelization of cdms.

— Tom

**Comment by painter1** [comment]
Charles asked for more detail, so here it is:

>>> bb=cdms2.createVariable( nbd, id=nbd.id )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/tvariable.py", line 827, in createVariable
    return TransientVariable(*args,**kargs)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/tvariable.py", line 168, in __init__
    axes = map(lambda x: x[0], data.getDomain())
AttributeError: 'numpy.int32' object has no attribute 'getDomain'

>>> nbd.shape
()
>>> nbd.getSlice()
10101
>>> type(nbd)
<class 'cdms2.fvariable.FileVariable'>
>>> type(nbd.subSlice())
<type 'numpy.int32'>
>>> type(nbd.getSlice())
<type 'numpy.int32'>

And Charles asked why anyone would want a scalar FileVariable?  I'm reading in all the variables of a large file; as FileVariable because most have to be changed in the file.  Sometimes I also need to create a TransientVariable from them.  A couple scalars are among the hundreds of variables.
