### ISSUE TITLE
cannot slice string variable from NetCDF file

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcdat#1333]
I have a NetCDF file (ACME output) with a string-valued variable.   With cdms2 I can read one character at a time, but no more.  Thus I can make a FileVariable out of it but not a Transient Variable.  For example:

_>>>_ time_written = f['time_written']
_>>>_ time_written.shape
(1, 8)
_>>>_ time_written[0,1]
'1'
_>>>_ time_written[0,2]
':'
_>>>_ time_written[0,:2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/variable.py", line 82, in __getitem__
    return AbstractVariable.__getitem__(self, key)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 1399, in __getitem__
    return self.getSlice(numericSqueeze=1, raw=0, isitem=1, *speclist)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 656, in getSlice
    result = self.subSlice(*specs, **keys)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 609, in subSlice
    id = self.id)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/tvariable.py", line 270, in __new__
    fill_value = numpy.array(fill_value).astype(dtype),
ValueError: could not convert string to float: N/A
 
_>>>_ f('time_written')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 45, in __call__
    return v(*args, **kwargs)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 155, in __call__
    grid=grid)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/selectors.py", line 195, in unmodified_select
    raw=raw)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 759, in subRegion
    return self.subSlice(*slicelist, **d)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 609, in subSlice
    id = self.id)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/tvariable.py", line 270, in __new__
    fill_value = numpy.array(fill_value).astype(dtype),
ValueError: could not convert string to float: N/A

**Comment by dnadeau4** [comment]
string variable is netCDF4, do we want to support string variables?   What are they used for?

**Comment by doutriaux1** [comment]
well we should, look at @painter1 example above

**Comment by doutriaux1** [comment]
I'm sure @durack1 has lots to say about that as well

**Comment by dnadeau4** [comment]
CDMS2 is trying to get the fill value from a string variable.  I think I have some ACME files on my disk, I'll give it a try.

**Comment by durack1** [comment]
@doutriaux1 you're right.. I'm certainly opinionated on this subject.. I've struggled with `cdms2` string handling in the past.. Would be happy to contribute my two cents when I'm back in
