### ISSUE TITLE
AMWG plot set 6 fails to display vectors

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1349]
@mcenerney1:
> In this graphic the vectors should be overlayed on the isofill plot. The isofill plot is displayed but the vectors are not.

**Comment by remram44** [comment]
Is this the same as #1338?

**Comment by mcenerney1** [comment]
It does bear a resemblance but I'm just not sure.

**Comment by remram44** [comment]
This is what I get trying plot 6 with default values, I'm gonna need more info to reproduce:
```
Traceback (most recent call last):
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 661, in buttonClicked
    self.applyClicked()
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 744, in applyClicked
    res = ps.results()
  File "/home/remram/uvcdat-builds/builds/d124bd78293d726bbf3d0c91779dfbff0f049ccf/install/lib/python2.7/site-packages/metrics/frontend/uvcdat.py", line 912, in results
    return self._results(newgrid)
  File "/home/remram/uvcdat-builds/builds/d124bd78293d726bbf3d0c91779dfbff0f049ccf/install/lib/python2.7/site-packages/metrics/packages/amwg/amwg.py", line 1549, in _results
    return self.plotspec_values[self.plotall_id]
KeyError: 'ft1_sample_data__STRESS_ANN'
```
Also are we sure this is in VisTrails at all? Looks unlikely...

**Comment by mcenerney1** [comment]
I don't get this error.  You need to select cam35_data for Dataset 1 and obs_data for Observation 1. Also for Obs set 1 select NCEP in the menu.  you should get 3 Isofill plots with no vectors.

**Comment by remram44** [comment]
Yeah I have no clue what this is or where to get the data. Cannot reproduce.

![amwg](https://cloud.githubusercontent.com/assets/426784/7970184/48b5edb4-0a0a-11e5-9964-38f30f9ccf4b.png)

**Comment by doutriaux1** [comment]
@remram44 when installing UVCDAT we create a directory in ${HOME}/uvcmetrics_test_data
Please look in there. @mcenerney1 should the data be in the above mentioned directory?

**Comment by mcenerney1** [comment]
Indeed it is. This is downloaded automatically. correct?

**Comment by remram44** [comment]
Couldn't this be under the install prefix? Filed #1362

As far as I can tell the data is at http://uv-cdat.llnl.gov/cdat/sample_data/uvcmetrics/, can I get the right thing without rebuilding UV-CDAT?

**Comment by mcenerney1** [comment]
The cam35_data is there.  Using the obs directory should work.

**Comment by doutriaux1** [comment]
look at the fetch_uvcmetrics_testdata.py.in configured file

**Comment by remram44** [comment]
Selecting obs_data_5.6 for observations 1 gives me this error message:
```
Traceback (most recent call last):
  File "/home/remram/uvcdat-builds/builds/9f25d777ca82a9bd383f232c26b579e4912c88e8/install/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 236, in setObs1Path
    self.prepareObs1()
  File "/home/remram/uvcdat-builds/builds/9f25d777ca82a9bd383f232c26b579e4912c88e8/install/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 369, in prepareObs1
    self.opts._opts['obs'][0]['filter'] = self.obs1_menu[self.observation1]
TypeError: 'bool' object has no attribute '__getitem__'
```

**Comment by mcenerney1** [comment]
What version of metrics? 
import metrics 
metrics.git.commit

**Comment by remram44** [comment]
I have uvcdat 2.2.0-45-g9f25d77, with VisTrails uvcdat-2.2.0-10-g22db59f. `metrics.git.commit` is 'uvcdat-2.2.0'.

**Comment by mcenerney1** [comment]
You have the right version.  As it turns out I've been working on that line of code in diagnosticsDockWidget.  There is a pull request request for the fix.  This bug surfaces when selecting an obs directory and then changing to a new one.  I haven't seen it ocurr in other situations.

**Comment by remram44** [comment]
I assigned this to me but still can't run diagnostics, same error on a fresh build of ef6b26ce. I am not looking into this. Also reportErrorDialog.py prints `urllib2.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR`.
