### ISSUE TITLE
matplotlib plot doesn't work

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1350]
I know it is kind of awkward, with the pylab package still kind-of-there in VisTrails, but matplotlib not built by default. However I installed it and found out I get an exception when trying to use the only plot available, `Histogram`. Should this just be removed?
```
Traceback (most recent call last):
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/gui/uvcdat/project_controller.py", line 534, in variable_was_dropped
    self.check_update_cell(sheetName,row,col,update)
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/gui/uvcdat/project_controller.py", line 913, in check_update_cell
    self.update_cell(sheetName, row, col, reuse_workflow)
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/gui/uvcdat/project_controller.py", line 995, in update_cell
    reuse_workflow)
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/gui/uvcdat/project_controller.py", line 1016, in update_workflow
    row, column)
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/packages/pylab/pipeline_helper.py", line 37, in build_plot_pipeline_action
    pip_str = core.db.io.serialize(plot_obj.workflow)
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/core/db/io.py", line 106, in serialize
    return db.services.io.serialize(object)
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/db/services/io.py", line 579, in serialize
    return daoList.serialize(object)
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/db/versions/v1_0_2/persistence/__init__.py", line 452, in serialize
    root = self.write_xml_object(object)
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/db/versions/v1_0_2/persistence/__init__.py", line 75, in write_xml_object
    res_node = self['xml'][obj.vtType].toXML(obj, node)
AttributeError: 'NoneType' object has no attribute 'vtType'
```
As far as I understand it, this meaks that plot_obj.workflow was None in `build_plot_pipeline_action()̀`.

**Comment by doutriaux1** [comment]
I'd say let's remove this.
