### ISSUE TITLE
cdtime.toRelativeTime - not yet implemented

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1371]
The following error message appears when attempting to use `toRelativeTime` on a pointer variable loaded using `fileHandle['var']` rather than `fileHandle('var')`

```
import cdms2 as cdm
f = '/work/durack1/Shared/obs_data/EN4/150519_EN4.1.1.g10_monthly_TAndS_190001-201504_5-5350m.xml'
uF = cdm.open(f)
t = uF['thetao'].getTime()

In[4]:t
Out[4]: 
   id: time
   Designated a time axis.
   units:  days since 1800-01-01 00:00:00
   Length: 1384
   First:  36539.5
   Last:   78632.0
   Other axis attributes:
      name_in_file: time
      datatype: Float
      partition: [[   0  120]
 [ 120  240]
 [ 240  360]
 [ 360  480]
 [ 480  600]
 [ 600  720]
 [ 720  840]
 [ 840  960]
 [ 960 1080]
 [1080 1200]
 [1200 1320]
 [1320 1384]]
      isvar: true
      calendar: gregorian
   Python id:  0x7fc4f06a4f50
t.toRelativeTime('days since 2000-1-1')
Traceback (most recent call last):
  File "<ipython-input-5-ce2d68cfda05>", line 1, in <module>
    t.toRelativeTime('days since 2000-1-1')
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/axis.py", line 852, in toRelativeTime
    self[i]=tmp2
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/axis.py", line 636, in __setitem__
    raise CDMSError, MethodNotImplemented
CDMSError: Method not yet implemented

In [6]:
```

**Comment by doutriaux1** [comment]
@durack1 what you want is:
```
In [1]: t=s.getTime()

In [2]: t.toRelativeTime("months since 1800")
```

**Comment by doutriaux1** [comment]
yours does not work because it is a FILE axis. That would mean write to the file. And indeed it is not implemented.

**Comment by durack1** [comment]
@doutriaux1 nope, this also doesn't seem to work..

```
f = '/work/durack1/Shared/obs_data/EN4/150519_EN4.1.1.g10_monthly_TAndS_190001-201504_5-5350m.xml'
uF = cdm.open(f)
t = uF.getAxis('time')
t.toRelativeTime('days since 2000-1-1')
relative time conversion
Traceback (most recent call last):
  File ".//make_ohcFromArgo.py", line 251, in <module>
    t.toRelativeTime('days since 2000-1-1')
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/axis.py", line 852, in toRelativeTime
    self[i]=tmp2
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/axis.py", line 636, in __setitem__
    raise CDMSError, MethodNotImplemented
cdms2.error.CDMSError: Method not yet implemented
```

**Comment by doutriaux1** [comment]
It is still a file axis
'''
t=t.clone ()
'''
Will convert from file axis to aci

**Comment by doutriaux1** [comment]
It is still a file axis
'''
t=t.clone ()
'''
Will convert from file axis to axis
