### ISSUE TITLE
Error when setting color scale for a_boxfill?

### ISSUE THREAD

**Issue by cameronsmith1** [UV-CDAT/uvcdat#1373]
I am trying to plot using a_boxfill in the UVCDAT GUI.   When I try to change the value range for the colorscale (ie level_1 & level_2) I get the error below.  I have tried it several times, with at least two different variables. 

Traceback (most recent call last):
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/gui/uvcdat/plot.py", line 78, in configureDone
    action)
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/gui/uvcdat/project_controller.py", line 1065, in plot_properties_were_changed
    self.update_plot_configure(sheetName, row, col)
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/gui/uvcdat/project_controller.py", line 849, in update_plot_configure
    widget = self.get_plot_configuration(sheetName,row,col)
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/gui/uvcdat/project_controller.py", line 907, in get_plot_configuration
    cell.plots)
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 76, in show_configuration_widget
    return CDMSPlotWidget(controller,version,plots,vars)
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1112, in __init__
    self.create_plot_widget()
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1237, in create_plot_widget
    stacked_widget = self.create_conf_widgets()
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1278, in create_conf_widgets
    self.add_conf_widget(plot_module)
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1285, in add_conf_widget
    show_buttons=False)
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/packages/uvcdat_cdms/widgets.py", line 32, in __init__
    self.mapAttributesToFunctions()
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/packages/uvcdat_cdms/widgets.py", line 156, in mapAttributesToFunctions
    self.attributes[fun] = self.getValueFromFunction(fun)
  File "/lustre/atlas2/csc121/world-shared/uvcdat/2015-05-06/vistrails/vistrails/packages/uvcdat_cdms/widgets.py", line 137, in getValueFromFunction
    value = ast.literal_eval(f.params[0].strValue)
  File "/lustre/atlas/world-shared/csc121/uvcdat/2015-05-06/lib/python2.7/ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "/lustre/atlas/world-shared/csc121/uvcdat/2015-05-06/lib/python2.7/ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

**Comment by doutriaux1** [comment]
@cameronsmith1 I just tried this localy and it seems to work. I will stop by your office tomorrow to double check what you are exactly doing. From the error message it seems it does not understand the values you typed in.
