### ISSUE TITLE
cdms2 cannot open files if xml generated by cdscan contains different base urls

### ISSUE THREAD

**Issue by cchriste** [UV-CDAT/uvcdat#1376]
Create cdat xml using `cdscan -x outfile.xml -f filelist.txt` where filelist.txt contains more than one base url, for example:
```
http://opendap.nccs.nasa.gov:9090/dods/OSSE/G5NR/Ganymed/7km/0.0625_deg/inst/inst30mn_3d_W_Nv
http://opendap.nccs.nasa.gov:80/dods/OSSE/G5NR/Ganymed/7km/0.0625_deg/inst/inst30mn_3d_V_Nv
```
(note the different port in the two urls)

Results are the same as in #1368: trying to read the actual data fails unable to open the file:
```
>>> dd=dv[10000][60]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/variable.py", line 82, in __getitem__
    return AbstractVariable.__getitem__(self, key)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/avariable.py", line 1399, in __getitem__
    return self.getSlice(numericSqueeze=1, raw=0, isitem=1, *speclist)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/avariable.py", line 656, in getSlice
    result = self.subSlice(*specs, **keys)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/avariable.py", line 549, in subSlice
    d = self.expertSlice (slicelist)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/variable.py", line 556, in expertSlice
    f = self.parent.openFile(filename,'r')
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/cdms2/dataset.py", line 754, in openFile
    f = Cdunif.CdunifFile(path,mode)
IOError: No error
```

**Comment by dnadeau4** [comment]
@cchriste The port 9090 is now closed at NCCS.  Do you have another example where you want to aggregate 2 files with 2 different URL?

**Comment by dnadeau4** [comment]
I tried with 2 different URL both at NCCS and it worked.  I think the problem happened when NCCS was transitioning between port 9090 and port 80 with their opendap server.

**Comment by doutriaux1** [comment]
@dnadeau4 did you take a look at #1368 ?

**Comment by dnadeau4** [comment]
I just did and got a fix for it.
