### ISSUE TITLE
import vcs error

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1429]
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/__init__.py", line 33, in <module>
    from utils import *
  File "/usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/utils.py", line 6, in <module>
    import boxfill
  File "/usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/boxfill.py", line 30, in <module>
    import Canvas
  File "/usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 73, in <module>
    import configurator
  File "/usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/configurator.py", line 3, in <module>
    import editors
  File "/usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/editors/__init__.py", line 1, in <module>
    import box
  File "/usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/editors/box.py", line 3, in <module>
    import priority
  File "/usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/editors/priority.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/uvcdat/05_20_15/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/editors/priority.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by aashish24** [comment]
Looks like a slightly older version. Can you update to the newer version and see if this goes away?

**Comment by doutriaux1** [comment]
http://prateekvjoshi.com/2013/02/15/non-ascii-character-syntax-error-in-python/

@aashish24 @mcenerney1 just merged master into his branch so he should be good.

**Comment by doutriaux1** [comment]
@mcenerney1 your branch with master merged into it works for me  on mac. master works on Linux.

I think you got a weird build, please try to build from scratch and let us know. Thanks. Closing for now. Please re-open if it is still happening for you

**Comment by mcenerney1** [comment]
do you want me to build from master or newdiagtest?

**Comment by doutriaux1** [comment]
newdiagtest the one where we merged master in

**Comment by doutriaux1** [comment]
but merge master in again, i oushed a flake8 bug fix in yesterday

**Comment by mcenerney1** [comment]
When I build uvcdat the directory uvcdat-testdata/baselines/metrics/ contains old baseline data.
How do I get the new data into this directory? Do I have to copy it over?

**Comment by doutriaux1** [comment]
did you create abranch for the new data? That's how you do it, you create a new branch and manually check it out.

**Comment by mcenerney1** [comment]
yes, it's in uvcdat-testdata in the newdiagsdata branch.
I just copied into the build directory and it's partially successful.
