### ISSUE TITLE
opening large file using opendap both GUI and command line fail

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1453]
I am trying to open a large file in UVCDAT (both GUI and command line) and I get an error:

[8:55am] Jerrys-MBP[/Volumes/MACOSX/CFSR/QC]python 
Python 2.7.9 (default, May 14 2015, 11:49:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdms2
>>> f=cdms2.open('http://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/CFSR/mon/atmos/prc.ncml')
>>> x=f('prc')
syntax error, unexpected WORD_STRING, expecting WORD_WORD
context: Error { code = 403; message = "Request too big=1115.0 Mbytes, max=500.0"^;};
ncvargets: ncid 65536: NetCDF: Access failure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 45, in __call__
    return v(*args, **kwargs)
  File "/usr/local/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 155, in __call__
    grid=grid)
  File "/usr/local/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/selectors.py", line 195, in unmodified_select
    raw=raw)
  File "/usr/local/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 759, in subRegion
    return self.subSlice(*slicelist, **d)
  File "/usr/local/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 549, in subSlice
    d = self.expertSlice (slicelist)
  File "/usr/local/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/fvariable.py", line 84, in expertSlice
    result = apply(self._obj_.getitem,slist)
IOError: Unknown error
>>>

**Comment by dnadeau4** [comment]
You need to set your  THREDDS OPeNDAP Configuration to allow bigger files to be transferred. 
This is the error I saw in the debugger

>syntax error, unexpected WORD_STRING, expecting WORD_WORD
>context: Error { code = 403; message = "Request too big=1115.0 Mbytes, max=500.0"^;};
>ncvargets: ncid 65536: NetCDF: Access failure

Here is an example for a 2Gb file transfer.  
  ```xml
 <Opendap>
    <ascLimit>50</ascLimit>
    <binLimit>20000</binLimit>
    <serverVersion>opendap/3.7</serverVersion>
  </Opendap>
```
You can also set the maximum files size in your Java/Tomcat configuration.  Here is the reference:

http://stommel.tamu.edu/~baum/bp.html#_thredds_opendap_configuration

**Comment by doutriaux1** [comment]
@potter2 alternatively, just get a smaller sample of a data at once (less time or smaller domain)
