### ISSUE TITLE
Ubuntu 14.10 won't run GUI

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1463]
I installed UVCDAT on Ubuntu 14.10 and I get this when I try to load a variable to plot:

Traceback (most recent call last):
  File "/usr/local/uvcdat/2.2.0/vistrails/vistrails/gui/uvcdat/variable.py", line 594, in defineVarCloseClicked
    self.getUpdatedVarCheck()
  File "/usr/local/uvcdat/2.2.0/vistrails/vistrails/gui/uvcdat/variable.py", line 630, in getUpdatedVarCheck
    self.getUpdatedVar(tid)
  File "/usr/local/uvcdat/2.2.0/vistrails/vistrails/gui/uvcdat/variable.py", line 729, in getUpdatedVar
    updatedVar = controller.create_exec_new_variable_pipeline(targetId)
  File "/usr/local/uvcdat/2.2.0/vistrails/vistrails/gui/uvcdat/project_controller.py", line 1188, in create_exec_new_variable_pipeline
    self.get_var_module(targetId, dummyCell, CDMSPipelineHelper)
  File "/usr/local/uvcdat/2.2.0/vistrails/vistrails/gui/uvcdat/project_controller.py", line 928, in get_var_module
    module = var.to_module(self.vt_controller)
  File "/usr/local/uvcdat/2.2.0/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 164, in to_module
    module = Variable.to_module(self, controller, identifier)
  File "/usr/local/uvcdat/2.2.0/vistrails/vistrails/packages/uvcdat/init.py", line 57, in to_module
    reg.get_descriptor_by_name(pkg_identifier, self.__class__.__name__))
  File "/usr/local/uvcdat/2.2.0/vistrails/vistrails/core/modules/module_registry.py", line 745, in get_descriptor_by_name
    raise MissingPackage(identifier)
MissingPackage: Missing package: gov.llnl.uvcdat.cdms

Is this something new?

**Comment by doutriaux1** [comment]
did you try to remove your ${HOME}/.uvcdat directory?

**Comment by potter2** [comment]
Thanks, I'll try that.

Sent from my iPad

On Jul 23, 2015, at 8:04 AM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


did you try to remove your ${HOME}/.uvcdat directory?

**Comment by durack1** [comment]
@potter2 did that work, can we close this issue?

**Comment by potter2** [comment]
Yes, please

Sent from my iPhone

On Aug 4, 2015, at 4:08 PM, Paul J. Durack <notifications@github.com<mailto:notifications@github.com>> wrote:


@potter2<https://github.com/potter2> did that work, can we close this issue?
