### ISSUE TITLE
Fonts not installed at the right location on Mac OSX

### ISSUE THREAD

**Issue by sankhesh** [UV-CDAT/uvcdat#1483]
I've been testing UV-CDAT on Mac OSX Yosemite (10.10.4)

UV-CDAT builds and installs fine. But when I try to run any python script, it throws a bunch of errors like:
```
failed Tt std Error font number not existing 1
failed Tt boldfont_tt15 Error font number not existing 1
failed Tt scatylab Error font number not existing 1
failed Tt font1 Error font number not existing 1
failed Tt font3 Error font number not existing 1
failed Tt qa Error font number not existing 1
failed Tt bigger Error font number not existing 1
failed Tt mwbotcenter Error font number not existing 1
failed Tt std Error font number not existing 1
failed Tt boldfont_tt15 Error font number not existing 1
failed Tt scatylab Error font number not existing 1
failed Tt font1 Error font number not existing 1
failed Tt font3 Error font number not existing 1
failed Tt qa Error font number not existing 1
failed Tt bigger Error font number not existing 1
failed Tt mwbotcenter Error font number not existing 1
Traceback (most recent call last):
  File "./541_patterns_support.py", line 80, in <module>
    x.plot(v, isof, tpl, continents=cont_type)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/Canvas.py", line 2525, in plot
    a = self.__plot(arglist, keyargs)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/Canvas.py", line 3839, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/VTKPlots.py", line 462, in plot
    vtk_backend_grid, vtk_backend_geo))
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 157, in plot
    self._plotInternal()
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/vcsvtk/isofillpipeline.py", line 360, in _plotInternal
    self._gm, t, z))
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/VTKPlots.py", line 611, in renderTemplate
    displays = tmpl.plot(self.canvas, data, gm, bg=self.bg)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/template.py", line 1461, in plot
    sub.textorientation)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/Canvas.py", line 2216, in createtextcombined
    x, y, height, angle, path, halign, valign, projection)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/manageElements.py", line 1597, in createtextcombined
    tc = textcombined.Tc(Tt_name, Tt_source, To_name, To_source)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/textcombined.py", line 310, in __init__
    self.Tt = texttable.Tt(Tt_name, Tt_name_src)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/texttable.py", line 382, in __init__
    self.font = src.font
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/texttable.py", line 220, in _setfont
    self._font = VCS_validation_functions.checkFont(self, 'font', value)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/VCS_validation_functions.py", line 207, in checkFont
    vcs.getfontname(value)
  File "/Users/sankheshjhaveri/Projects/uvcdat/bld/install/lib/python2.7/site-packages/vcs/utils.py", line 120, in getfontname
    raise Exception("Error font number not existing %i" % number)
Exception: Error font number not existing 1
```

In short, the issue is in [install.py.in] (https://github.com/UV-CDAT/uvcdat/blob/21e26d07b78f9a1940867362d68c0705fad1d550/CMake/cdat_modules_extra/install.py.in#L742-L758)

The target_prefix in the above link points to ``<build>/install/Library/Frameworks/Python.framework/Versions/2.7`` on my Mac instead of ``<build>/install`` on my Linux box.

For those interested, the fonts are installed to ``<build>/install/bin`` by [CMake/install.py.in] (https://github.com/UV-CDAT/uvcdat/blob/21e26d07b78f9a1940867362d68c0705fad1d550/CMake/cdat_modules_extra/install.py.in#L757) and then to ``$HOME/.uvcdat`` by [install_vcs.py] (https://github.com/UV-CDAT/uvcdat/blob/21e26d07b78f9a1940867362d68c0705fad1d550/Packages/vcs/Lib/install_vcs.py#L140-L155). But, the fonts are never installed under ``<build>/install/bin`` on the Mac.

**Comment by durack1** [comment]
@sankhesh I wonder what other goodies and changes are in store with the `OS X 10.11 Public Beta 4` that is currently available and will likely make it into the final release.. I know they've updated the system `Python` to `2.7.10`, but wonder what else has changed.. Might be worth adding that to the buildbot test list (#1384)

**Comment by sankhesh** [comment]
@durack1 

:+1: for adding to buildbot test list

Although, I am not sure if this issue is related to a specific OS X version.

**Comment by doutriaux1** [comment]
@sankhesh does that still occurs for you? All other macs seems to be ok.

**Comment by sankhesh** [comment]
Nope. I think it was homebrew messing up my path. I'll close it
