### ISSUE TITLE
colormapEditor Widget error

### ISSUE THREAD

**Issue by dnadeau4** [UV-CDAT/uvcdat#1570]
It seems that getcolormap is still broken in the gui.  I loaded and display a dataset and when I want to edit the colorbar I get the following error.

:bomb:
```
cat filelist2.txt 
http://ferret.pmel.noaa.gov/thredds/dodsC/data/PMEL/levitus_climatology.nc
cdscan -x outfile2.xml -f filelist2.txt


uvcdat->open file(outfile2.xml)-> select SALT-> barfill
Click on picture.  Select colorbar "palette"  (top right corner)
```
:boom: :boom:

```
Traceback (most recent call last):
  File "/software/run/uvcdatall/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1883, in triggeredSlot
    _app.uvcdatWindow.colormapEditor.activateFromCell(canvas)
  File "/software/run/uvcdatall/vistrails/vistrails/gui/uvcdat/colormapEditorWidget.py", line 189, in activateFromCell
    self.setColorsFromCanvas()
  File "/software/run/uvcdatall/vistrails/vistrails/gui/uvcdat/colormapEditorWidget.py", line 249, in setColorsFromCanvas
    r, g, b = self.activeCanvas.getcolorcell(n)
  File "/software/run/uvcdatall/lib/python2.7/site-packages/vcs/Canvas.py", line 6165, in getcolorcell
    return vcs.getcolorcell(args[0], self)
  File "/software/run/uvcdatall/lib/python2.7/site-packages/vcs/utils.py", line 1473, in getcolorcell
***** cmap = vcs.getcolormap(obj.colormap)
  File "/software/run/uvcdatall/lib/python2.7/site-packages/vcs/manageElements.py", line 1934, in getcolormap
    raise ValueError('Error -  The argument must be a string.')
ValueError: Error -  The argument must be a string.
```

**Comment by doutriaux1** [comment]
OK will fix in the morning and then tag rc1 thx for reporting.
