### ISSUE TITLE
Build fails due to CRYPTOGRAPHY

### ISSUE THREAD

**Issue by stefraynaud** [UV-CDAT/uvcdat#1589]
Current master fails on SUSE Linux Enterprise Server 11 (x86_64) due to python package CRYPTOGRAPHY.

Here are the logs.

OUT
```
running install
running build_ext
building '_Cryptography_cffi_444d7397xa22f8491' extension
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home1/caparmor/sraynaud/soft/uvcdat-092015/Externals/include -I/home1/caparmor/sraynaud/soft/uvcdat-092015/Externals/lib/libffi-3.1/include -fPIC -I/home1/caparmor/sraynaud/soft/uvcdat-092015/include/python2.7 -c cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c -o /home1/caparmor/sraynaud/soft/src/uvcdat/build/build/CRYPTOGRAPHY/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.o
```

ERR
```
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c: In function '_cffi_const_NID_ecdsa_with_SHA224':
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c:7904: error: 'NID_ecdsa_with_SHA224' undeclared (first use in this function)
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c:7904: error: (Each undeclared identifier is reported only once
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c:7904: error: for each function it appears in.)
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c: In function '_cffi_const_NID_ecdsa_with_SHA256':
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c:7923: error: 'NID_ecdsa_with_SHA256' undeclared (first use in this function)
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c: In function '_cffi_const_NID_ecdsa_with_SHA384':
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c:7942: error: 'NID_ecdsa_with_SHA384' undeclared (first use in this function)
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c: In function '_cffi_const_NID_ecdsa_with_SHA512':
cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c:7961: error: 'NID_ecdsa_with_SHA512' undeclared (first use in this function)
Traceback (most recent call last):
  File "setup.py", line 174, in <module>
    "test": PyTest,
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 100, in finalize_options
    self.distribution.ext_modules = get_ext_modules()
  File "setup.py", line 68, in get_ext_modules
    OpenSSLBinding().ffi.verifier.get_extension(),
  File "/home1/caparmor/sraynaud/soft/src/uvcdat/build/build/CRYPTOGRAPHY/cryptography/hazmat/bindings/openssl/binding.py", line 87, in __init__
    self._ensure_ffi_initialized()
  File "/home1/caparmor/sraynaud/soft/src/uvcdat/build/build/CRYPTOGRAPHY/cryptography/hazmat/bindings/openssl/binding.py", line 106, in _ensure_ffi_initialized
    libraries=libraries,
  File "/home1/caparmor/sraynaud/soft/src/uvcdat/build/build/CRYPTOGRAPHY/cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
    extra_link_args=extra_link_args,
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/site-packages/cffi-0.8.2-py2.7-linux-x86_64.egg/cffi/api.py", line 341, in verify
    lib = self.verifier.load_library()
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/site-packages/cffi-0.8.2-py2.7-linux-x86_64.egg/cffi/verifier.py", line 74, in load_library
    self._compile_module()
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/site-packages/cffi-0.8.2-py2.7-linux-x86_64.egg/cffi/verifier.py", line 139, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/site-packages/cffi-0.8.2-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 25, in compile
    outputfilename = _build(tmpdir, ext)
  File "/home1/caparmor/sraynaud/soft/uvcdat-092015/lib/python2.7/site-packages/cffi-0.8.2-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 50, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

**Comment by doutriaux1** [comment]
do you have openssl devel installed?
any chance we can ask you to set this machine (or another one as one of our bot slaves for continuous testing of installs?)

**Comment by stefraynaud** [comment]
How to check that these devel packages are installed?

How to integrate this machine in your continuous testing?

**Comment by aashish24** [comment]
@stefraynaud it would be great to have a SUSE dashboard or buildbot slave +1

**Comment by stefraynaud** [comment]
Ok, how to configure buildbot to connect to your master?

**Comment by doutriaux1** [comment]
@stefraynaud please take a look at: https://github.com/UV-CDAT//uvbot I will email you our bot-key.

Once your slave is up and can pass the "how can I help you" test I can add it to our master list of slaves.

You have control of which options you want to send to your slave (i.e which UV-CDAT configuration to build)

**Comment by stefraynaud** [comment]
In fact, the buildbot/slave solution is not optimal all system since it requires to open a port accesible from outside, which is not always possible, for instance where I work and on the IFREMER supercomputer.
However, we have our own CI based on jenkins, and a solution would be to format and send reports to the master.

**Comment by doutriaux1** [comment]
@stefraynaud the bot/slave idea was not for this on/off but just in general so that we never break it again.
If your jenkins can send report to github that would be awesome.
