### ISSUE TITLE
Version 2.4.0 rc2 bug in color maps etc.

### ISSUE THREAD

**Issue by glpotter** [UV-CDAT/uvcdat#1606]
Change background color then I changed the colormap got this:

Traceback (most recent call last):
  File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/configurator.py", line 236, in release
    self.create()
  File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/configurator.py", line 843, in create
    self.activate(dp, dp.backend[key][0], key)
  File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/configurator.py", line 428, in activate
    self)
  File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/editors/text.py", line 91, in __init__
    self.update()
  File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/editors/text.py", line 129, in update
    cmap=cmap)
  File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 962, in prepTextProperty
    if tt.colormap is not None:
AttributeError: 'Tc' object has no attribute 'colormap'

**Comment by doutriaux1** [comment]
@glpotter how did you `change the background color` ? In the gui editor mode?

**Comment by glpotter** [comment]
yes


Jerry Potter
UC Davis
Department of Earth and Planetary Sciences
One Shields Ave
Davis, CA 95616
(707) 315-8314
jpotter@ucdavis.edu

**Comment by doutriaux1** [comment]
hum... works for me. I will need a little more details. I'm using cult with boxfill "default", then change background red value (tried to both close or leave open, makes no difference) then click colormap editor and change the palette. Everything works here. Which os?

**Comment by glpotter** [comment]
10.10.. I may not be able to reproduce it either.. delete the bug report until I can reproduce it.


> On Oct 12, 2015, at 3:42 PM, Charles Doutriaux <notifications@github.com> wrote:
> 
> hum... works for me. I will need a little more details. I'm using cult with boxfill "default", then change background red value (tried to both close or leave open, makes no difference) then click colormap editor and change the palette. Everything works here. Which os?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/UV-CDAT/uvcdat/issues/1606#issuecomment-147541871>.
> 

Jerry Potter
UC Davis
Department of Earth and Planetary Sciences
One Shields Ave
Davis, CA 95616
(707) 315-8314
jpotter@ucdavis.edu

**Comment by doutriaux1** [comment]
hum... Let's just wait. I will look at your trace and see if I can create a test that re-triggers this.

**Comment by doutriaux1** [comment]
@chaosphere2112 the following bit of output:
```
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/editors/text.py", line 129, in update
cmap=cmap)
File "/Users/potter/uvcdat/build-uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 962, in prepTextProperty
if tt.colormap is not None:
AttributeError: 'Tc' object has no attribute 'colormap'
```
worries me `tt.colormap` sugests it should by a texttable object, but the error says `Tc` which means it is a colormap object.

**Comment by chaosphere2112** [comment]
@doutriaux1 Tc is also the name of TextCombined objects. I was passing them into vcs2vtk in laziness (instead of getting the To and Tt from it). I updated this to not do so anymore.

**Comment by doutriaux1** [comment]
Your'e right Cp are the colormaps...
