### ISSUE TITLE
Diagnosis broken from GUI

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1648]
Going to Diagnosis menu -> Select AMWG -> set path to `cam_output` in our share/uvcmetrics directory

I get:
```
Traceback (most recent call last):
  File "/lgm/uvcdat/2015-10-21/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 273, in setDS1Path
    self.prepareDS1()
  File "/lgm/uvcdat/2015-10-21/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 300, in prepareDS1
    self.ft1 = self.dsfiles1.setup_filetable()
  File "/lgm/uvcdat/2015-10-21/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metrics/fileio/findfiles.py", line 199, in setup_filetable
    ftid = self.short_name()
  File "/lgm/uvcdat/2015-10-21/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metrics/fileio/findfiles.py", line 340, in short_name
    if len(self.opts[self._type]) > self._index:
  File "/lgm/uvcdat/2015-10-21/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metrics/frontend/options.py", line 90, in __getitem__
    return self._opts[opt]
KeyError: None
```

**Comment by doutriaux1** [comment]
@isubsmith and @mcenerney1  can you also please take a look and help @painter1.

@williams13 do we still want the diags from the GUI?

**Comment by isubsmith** [comment]
I'm sure the UVCDAT code is out of sync with changes in diagnostics code. This looks fairly simple (changes to the options data structure), but I don't know where the UVCDAT code is any more and I don't know how to check out the right version of it either.

If you can help with that I can probably look at it, though I have other commitments all afternoon :(

**Comment by isubsmith** [comment]
I found diagnosticsDockWidget.py. Send me a branch name and/or sha1 and I can grab the latest version of it. I probably won't be able to fix this before morning though.

**Comment by chaosphere2112** [comment]
@isubsmith The [UV-CDAT/Vistrails](https://github.com/UV-CDAT/vistrails) branch that is in use is `uvcdat-master`

**Comment by painter1** [comment]
I fixed the problem.  The fix is in uvcmetrics, devel branch.   All that remains is to make sure that the next UV-CDAT build includes this version of the diagnostics.  I'll leave the issue open until someone can confirm that that will happen.

**Comment by doutriaux1** [comment]
@painter1 it is still pointing to `devel` so it will be in.
