### ISSUE TITLE
Numpy issue during uvcdat build

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1694]
Following the documentation
cmake ../uvcdat -DCDAT_BUILD_PARALLEL=ON 
make -j4 

gets the following 

[ 53%] Performing build step for 'NUMPY'
-- setuptools install command succeeded.  See also /Users/mcenerney1/build_11_16_15/setuptools-prefix/src/setuptools-stamp/setuptools-install-*.log

[ 53%] Completed 'setuptools'
[ 53%] Built target setuptools
CMake Error at /Users/mcenerney1/build_11_16_15/NUMPY-prefix/src/NUMPY-stamp/NUMPY-build.cmake:56 (message):
  CTEST_FULL_OUTPUT

   Command failed: 1
   '/usr/local/bin/cmake' '-P' '/Users/mcenerney1/build_11_16_15/CMake/NUMPY_make_step.cmake'
   From /Users/mcenerney1/build_11_16_15/NUMPY-prefix/src/NUMPY-stamp/NUMPY-build-out.log

  -------------------------------------------------

  -------------------------------------------------

   From /Users/mcenerney1/build_11_16_15/NUMPY-prefix/src/NUMPY-stamp/NUMPY-build-err.log

  -------------------------------------------------

  Running from numpy source directory.

  
  /usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267:
  UserWarning: Unknown distribution option: 'test_suite'

    warnings.warn(msg)

  
  /usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267:
  UserWarning: Unknown distribution option: 'define_macros'

    warnings.warn(msg)

  Traceback (most recent call last):

    File "setup.py", line 251, in <module>
      setup_package()
    File "setup.py", line 243, in setup_package
      setup(**metadata)
    File "/Users/mcenerney1/build_11_16_15/build/NUMPY/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/mcenerney1/build_11_16_15/build/NUMPY/numpy/distutils/command/build.py", line 39, in run
      old_build.run(self)
    File "/usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/mcenerney1/build_11_16_15/build/NUMPY/numpy/distutils/command/build_src.py", line 153, in run
      self.build_sources()
    File "/Users/mcenerney1/build_11_16_15/build/NUMPY/numpy/distutils/command/build_src.py", line 164, in build_sources
      self.build_library_sources(*libname_info)
    File "/Users/mcenerney1/build_11_16_15/build/NUMPY/numpy/distutils/command/build_src.py", line 299, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "/Users/mcenerney1/build_11_16_15/build/NUMPY/numpy/distutils/command/build_src.py", line 386, in generate_sources
      source = func(extension, build_dir)
    File "numpy/core/setup.py", line 686, in get_mathlib_info
      raise RuntimeError("Broken toolchain: cannot link a simple C program")

  RuntimeError: Broken toolchain: cannot link a simple C program

  [ERROR] NUMPY Errors detected:

  

  non-existing path in 'numpy/f2py': 'docs'

  non-existing path in 'numpy/f2py': 'f2py.1'

  F2PY Version 2

  blas_opt_info:

  blas_mkl_info:

    libraries mkl,vml,guide not found in ['/usr/local/uvcdat/11_16_2015/Library/Frameworks/Python.framework/Versions/2.7/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

**Comment by aashish24** [comment]
@mcenerney1 what version of xcode is this? Also, do you have command line tools installed?

**Comment by mcenerney1** [comment]
6.3

**Comment by aashish24** [comment]
and you have installed command line tools?

**Comment by doutriaux1** [comment]
@aashish24 all the bots have been showing the same results for some days now. My mac still works, I'm taking care of this now.

**Comment by aashish24** [comment]
@doutriaux1 I didn't see this problem on Friday bots but it may be that I am missing references to the bots that you found the issue. Thanks,

**Comment by doutriaux1** [comment]
I saw them on some builds going as far back as thursday or wednesday. Was only on mac1 at first now seems to be on all macs. I suspect a setup tools standard issue where it writes in the `.pth` file from 2 instances at the same time and only the last/fisrt one is stored.

**Comment by mcenerney1** [comment]
make -j8 also fails.

**Comment by doutriaux1** [comment]
I'm closing in on a solution (I hope)

**Comment by mcenerney1** [comment]
I'm trying make. I'll let you know next week.

**Comment by mcenerney1** [comment]
make fails

**Comment by aashish24** [comment]
@mcenerney1 as suspected this was an issue with command line tools and xcode. So I am closing this issue now.

**Comment by aashish24** [comment]
@williams13 @doutriaux1 feel free to open this if needed.
