### ISSUE TITLE
facing issue when i tried to run uvcdat (requirements.MissingRequirement: Missing Requirement: PyQt4.QtGui)

### ISSUE THREAD

**Issue by somanathmoharana** [UV-CDAT/uvcdat#1760]
Hi ,
 I installed uvcdat from the source tar. after I installation when i tried to run uvcdat i am facing the issue. 
Location: /home/apps/cesm/depedencies/uvcdat
Traceback (most recent call last):
  File "/home/apps/cesm/depedencies/uvcdat/vistrails/vistrails/uvcdat.py", line 82, in <module>
    gui.requirements.check_pyqt4()
  File "/home/apps/cesm/depedencies/uvcdat/vistrails/vistrails/gui/requirements.py", line 42, in check_pyqt4
    require_python_module('PyQt4.QtGui')
  File "/home/apps/cesm/depedencies/uvcdat/vistrails/vistrails/core/requirements.py", line 72, in require_python_module
    raise MissingRequirement(module_name)
core.requirements.MissingRequirement: Missing Requirement: PyQt4.QtGui.

But PyQt is present in the system. What I need to do to resolve this issue ???

**Comment by doutriaux1** [comment]
Hi @somanathmoharana which OS are you running this under? Which `source tar` are you talking about? By `PyQt present on the system` do you mean in your system python or the python that you just installed? (you can look under /home/apps/cesm/depedencies/uvcdat/lib/python2.7/site-packages (or similar path). 
Thanks for the clarifications.

**Comment by doutriaux1** [comment]
@somanathmoharana is this working for you now?

**Comment by somanathmoharana** [comment]
Hi @doutriaux1 ,
 Thanks for the help i installed it PyQt4 and that issue is resolved.but still I cant run uvcdat. Now I am stuck with another error i.e.
Location: /home/apps/cesm/depedencies/uvcdat
2016-01-09 17:58:28,840 CRITICAL:
/home/apps/cesm/depedencies/uvcdat/vistrails/vistrails/gui/application.py, line                                   838
Found another instance of VisTrails running
2016-01-09 17:58:28,840 CRITICAL:
/home/apps/cesm/depedencies/uvcdat/vistrails/vistrails/gui/application.py, line                                   840
Will send parameters to main instance []
2016-01-09 17:58:28,840 CRITICAL:
/home/apps/cesm/depedencies/uvcdat/vistrails/vistrails/gui/application.py, line                                   784
Connection failed: QLocalSocket::connectToServer: Connection refused
Traceback (most recent call last):
  File "/home/apps/cesm/depedencies/uvcdat/vistrails/vistrails/uvcdat.py", line                                   97, in <module>
    app = gui.application.get_vistrails_application()
AttributeError: 'module' object has no attribute 'get_vistrails_application'
.....................................................
The source tar I am using is uvcdat-2.2.0.tar.gz and the os is Red Hat Enterprise Linux Server release 6.6 (Santiago).
Thanks again

**Comment by doutriaux1** [comment]
hi @somanathmoharana it appears that your install did not install vistrails/qt. ON RH6 you cannot use the system Qt as it is bad (not full). You will need to use the Qt provided with our sources please refer to install and prerequisites section at: http://uvcdat.llnl.gov/installing.html and specifically at: https://github.com/UV-CDAT/uvcdat/wiki/Install-on-RedHat-or-CentOS
Unfortunately I think you will need to do a fresh install.
