### ISSUE TITLE
Error regridding curvedGrid

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1809]
```python
# Ocean grid
dataFileT   = '/CESM1-CAM5/thetao_Omon_CESM1-CAM5_historicalMisc_r1i1p17_196001-201312.nc'
dataFileT_h = cdm.open(dataFileT)
thetao = dataFileT_h('thetao',time=slice(0,1))
thetao.getGrid()
Out[103]: <TransientCurveGrid, id: grid_10, shape: (384, 320)>

# Atmospheric grid
dataFileAtmos = '/work/cmip5/historical/atm/mo/tas/cmip5.CESM1-CAM5.historical.r1i1p1.mo.atm.Amon.tas.ver-v20120608.latestX.xml'
dataFileAtmos_h = cdm.open(dataFileAtmos)
tas = dataFileAtmos_h('tas',time=slice(0,1))
tas.getGrid()
Out[104]: 
Grid has Python id 0x7f07739ac9d0.
Gridtype: generic
Grid shape: (192, 288)
Order: yx

new = thetao.regrid(tas,regridTool='esmf')
Traceback (most recent call last):
  File "<ipython-input-105-ac79cda83841>", line 1, in <module>
    new = thetao.regrid(tas,regridTool='esmf')
  File "/usr/local/uvcdat/2015-12-21_all/lib/python2.7/site-packages/cdms2/avariable.py", line 1116, in regrid
    **keywords)
  File "/usr/local/uvcdat/2015-12-21_all/lib/python2.7/site-packages/cdms2/mvCdmsRegrid.py", line 340, in __init__
    dstCoords = _getCoordList(dstGrid)
  File "/usr/local/uvcdat/2015-12-21_all/lib/python2.7/site-packages/cdms2/mvCdmsRegrid.py", line 218, in _getCoordList
    cgrid = grid.toCurveGrid()
AttributeError: 'TransientVariable' object has no attribute 'toCurveGrid'
```

**Comment by doutriaux1** [comment]
@danlipsa I can reproduce this, taking out the missing values leads to data to being plotted but no continents.I attached the netcdf file

```python
import vcs
import cdms2
f=cdms2.open("bad_heat.nc")
h=f("heat")
x.plot(h)
```
leads to
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-9472754c4355> in <module>()
----> 1 x.plot(h)

/usr/local/uvcdat/2.4.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.pyc in plot(self, *actual_args, **keyargs)
   2422 
   2423         # Plot the data
-> 2424         a = self.__plot(arglist, keyargs)
   2425 
   2426         if "continents_line" in keyargs:

/usr/local/uvcdat/2.4.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.pyc in __plot(self, arglist, keyargs)
   3745                         **keyargs)
   3746             else:
-> 3747                 returned_kargs = self.backend.plot(*arglist, **keyargs)
   3748                 if not keyargs.get("donotstoredisplay", False):
   3749                     nm, src = self.check_name_source(

/usr/local/uvcdat/2.4.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VTKPlots.pyc in plot(self, data1, data2, template, gtype, gname, bg, *args, **kargs)
    526         if pipeline is not None:
    527             returned.update(pipeline.plot(data1, data2, tpl,
--> 528                                           vtk_backend_grid, vtk_backend_geo))
    529         elif gtype in ["3d_scalar", "3d_dual_scalar", "3d_vector"]:
    530             cdms_file = kargs.get('cdmsfile', None)

/usr/local/uvcdat/2.4.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.pyc in plot(self, data1, data2, tmpl, grid, transform)
    286 
    287         # Generate a mapper to render masked data:
--> 288         self._createMaskedDataMapper()
    289 
    290         # Create the polydata filter:

/usr/local/uvcdat/2.4.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.pyc in _createMaskedDataMapper(self)
    331         self._maskedDataMapper = vcs2vtk.putMaskOnVTKGrid(
    332             self._data1, self._vtkDataSet, color, self._useCellScalars,
--> 333             deep=False)
    334 
    335         self._resultDict["vtk_backend_missing_mapper"] = (

/usr/local/uvcdat/2.4.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/vcs2vtk.pyc in putMaskOnVTKGrid(data, grid, actorColor, cellData, deep)
    113                 attributes2.SetPedigreeIds(attributes.GetPedigreeIds())
    114                 vtkmask = vtk.vtkIntArray()
--> 115                 vtkmask.SetNumberOfTuples(attributes2.GetPedigreeIds().GetNumberOfTuples())
    116             vtkmask.SetName("scalar")
    117             attributes2.RemoveArray(vtk.vtkDataSetAttributes.GhostArrayName())

AttributeError: 'NoneType' object has no attribute 'GetNumberOfTuples'
```

Whereas 
```python
import vcs
import cdms2
f=cdms2.open("bad_heat.nc")
h=f("heat")
h[:]=h.filled(0.0)
x.plot(h)
```

leads to:

![heat](https://cloud.githubusercontent.com/assets/2781425/12755446/46446666-c984-11e5-9153-ad9614a38239.png)


[bad.zip](https://github.com/UV-CDAT/uvcdat/files/114235/bad.zip)

**Comment by doutriaux1** [comment]
@danlipsa note that this used to work with rc2.

**Comment by doutriaux1** [comment]
@danlipsa there are still some obvious `cell splitting` issue left with this file

**Comment by durack1** [comment]
@danlipsa @doutriaux1 I would strongly recommend that a number of the CMIP5 ocean (and atmosphere) grids are used routinely in tests for any new or bug-fixed functionality, just using a single grid/input test is unlikely to catch the error that is described above..

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/uvcdat/pull/1829
