### ISSUE TITLE
Graphics error with MESA

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1844]
While plotting a large amount of data with MESA, I get the following.

Traceback (most recent call last):
  File "/opt/nfs/mcenerney1//uvcmetrics/src/python/frontend/diags.py", line 590, in <module>
    run_diagnostics_from_options(o)
  File "/opt/nfs/mcenerney1//uvcmetrics/src/python/frontend/diags.py", line 96, in run_diagnostics_from_options
    run_diagnostics_from_filetables( opts, modelfts, obsfts )
  File "/opt/nfs/mcenerney1//uvcmetrics/src/python/frontend/diags.py", line 513, in run_diagnostics_from_filetables
    units=getattr(var,'units',''), source=rsr.source )
  File "/opt/nfs/mcenerney1/02_17_16/lib/python2.7/site-packages/metrics/frontend/amwg_plotting.py", line 19, in amwg_plot_spec_vcs_plot
    canvas.plot( var, gm, tm, *args, **kwargs )
  File "/opt/nfs/mcenerney1/02_17_16/lib/python2.7/site-packages/vcs/Canvas.py", line 2424, in plot
    a = self.__plot(arglist, keyargs)
  File "/opt/nfs/mcenerney1/02_17_16/lib/python2.7/site-packages/vcs/Canvas.py", line 3747, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/opt/nfs/mcenerney1/02_17_16/lib/python2.7/site-packages/vcs/VTKPlots.py", line 539, in plot
    vtk_backend_grid, vtk_backend_geo))
  File "/opt/nfs/mcenerney1/02_17_16/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 296, in plot
    self._plotInternal()
  File "/opt/nfs/mcenerney1/02_17_16/lib/python2.7/site-packages/vcs/vcsvtk/isofillpipeline.py", line 49, in _plotInternal
    prepedContours = self._prepContours()
  File "/opt/nfs/mcenerney1/02_17_16/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 248, in _prepContours
    tmpLevels.append(L)
UnboundLocalError: local variable 'L' referenced before assignment

**Comment by mcenerney1** [comment]
with or without MESA

**Comment by danlipsa** [comment]
@mcenerney1 Can we have the script and the data file you used to get this error? Thanks!

**Comment by danlipsa** [comment]
@doutriaux1 @mcenerney1 Is this still a bug?

**Comment by doutriaux1** [comment]
@danlipsa I don't know.

**Comment by danlipsa** [comment]
@mcenerney1 Is there a script and dataset that we can use to reproduce this bug?
