### ISSUE TITLE
Can't add missing value attribute to netcdf file variable

### ISSUE THREAD

**Issue by stefraynaud** [UV-CDAT/uvcdat#1853]
This code fails when writing a simple variable to a file:
```python
import cdms2, MV2
f = cdms2.open(__file__[:-2]+'.nc', 'w')
f.write(MV2.ones(1))
f.close()
```

Output:
```
Traceback (most recent call last):
  File "bug_write_netcdf.py", line 6, in <module>
    f.write(MV2.ones(1))
  File "/home1/caparmor/sraynaud/soft/uvcdat/lib/python2.7/site-packages/cdms2/dataset.py", line 1728, in write
    id=varid, extend=extend, fill_value=fill_value, index=index)
  File "/home1/caparmor/sraynaud/soft/uvcdat/lib/python2.7/site-packages/cdms2/dataset.py", line 1661, in createVariableCopy
    setattr(newvar, attname, attval)
  File "/home1/caparmor/sraynaud/soft/uvcdat/lib/python2.7/site-packages/cdms2/fvariable.py", line 137, in __setattr__
    setattr(self._obj_, name, value)
ValueError: Invalid data-type for array
```
where the attribute name is "missing_value".

It fails only on a particular installation of uvcdat close to 2.0.0, that already worked in the past.
Among the things that changed since it worked is combined an update of matplotlib and numpy using pip -U. Maybe a solution would be an appropriate downgrade of numpy without breaking dependent packages. 

Is numpy the problem and what is the maximal version of numpy this version of uvcdat/cdunif can support?

Note that I can't update my version of UVCDAT since the installation fails due to the problematic CRYPTOGRAPHY package whose installation fails for unkown reasons (already reported here).

**Comment by doutriaux1** [comment]
@stefraynaud works for me out of master/2.4.0 I'm leaving it open for a little while in case somebody else can reproduce.

**Comment by dnadeau4** [comment]
It worked for me as well,  it might have been fixed with the latest CDMS2 patch to delete attributes.

```
 ncdump -v axis_0 issue1853.nc
netcdf a. {
dimensions:
	axis_0 = 1 ;
variables:
	double axis_0(axis_0) ;
	double variable_2(axis_0) ;
		variable_2:missing_value = 1.e+20 ;
		variable_2:_FillValue = 1.e+20 ;

// global attributes:
		:Conventions = "CF-1.0" ;
data:

 axis_0 = 0 ;
}
```

**Comment by stefraynaud** [comment]
@doutriaux1 @dnadeau4 There is no doubt that this basic test will pass in all normal UVCDAT configuration. What I would like to emphasize is that it seems I broke my configuration probably when I updated numpy, but I'm not sure. Do you think uvcdat-2.2.0 can be incompatible with a recent version of numpy without a re-installation of uvcdat ?

**Comment by doutriaux1** [comment]
@stefraynaud yes it is 100% sure they're not compatible, @dnadeau4 is working hard bringing the latest numpy in.

**Comment by dnadeau4** [comment]
I fixed the mask problem, but still have about 4 issues to go through.  Right now, all might time is going to CMOR3 for CMIP6.  The first problem was that MV2.copy was overloading numpy.copy and the _mask was broken.  I had an appropriate error message and line number from numpy which made the issue difficult to solve.

**Comment by doutriaux1** [comment]
@dnadeau4 any chance you can get to this before June 7th?

**Comment by dnadeau4** [comment]
I'll try to do it by then.


Denis

**Comment by doutriaux1** [comment]
thanks! No pressure though, don't drop anything for this.

**Comment by dnadeau4** [comment]
Fix in #2125 numpy1_11 pr.  Preparing a test.
