### ISSUE TITLE
Can't set colormap index using color name

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1860]
```python
import vcs
cmap = vcs.createcolormap()
cmap.index[5] = "blue"
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/uvcdat/2.4.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/colormap.py", line 170, in __setitem__
    'Must be either a list object, tuple object, or integer value.')
ValueError: Must be either a list object, tuple object, or integer value.
```

**Comment by aashish24** [comment]
createcolormap create an array of rgba now. Was it working before?

**Comment by chaosphere2112** [comment]
Needs to also support `setcolorcell()` and `setcolorindex()`

**Comment by chaosphere2112** [comment]
`setindex()`*
