### ISSUE TITLE
UV-CDAT can't open valid CF-1 file.

### ISSUE THREAD

**Issue by dnadeau4** [UV-CDAT/uvcdat#1888]
The following file cannot be open properly with uvcdat gui.  
(http://crunchy.llnl.gov/nadeau1/ezCMOR/data/tas_Amon_abrupt4xCO2_GCCM1_r1p1f1_197305-197305.nc)

I am not sure why UV-CDAT says that the coordinate interval has no data since all time and time_bound values are fine.
```python
 import cdms2

 f=cdms2.open("CMIP6/PCMDI/GCCM1/PMIP/abrupt4xCO2/no-driver/r1p1f1/Amon/tas/v20160323/tas_Amon_abrupt4xCO2_GCCM1_r1p1f1_197305-197305.nc")

 d=f['tas']

 d.getTime()
   id: time
   Designated a time axis.
   units:  days since 1970-01-01 00:00:00
   Length: 1
   First:  1246.29166667
   Last:   1246.29166667
   Other axis attributes:
      long_name: time
      standard_name: time
      calendar: gregorian
      axis: T
   Python id:  0x7f7848c50810

 d.getTime().getBounds()
array([[ 1231.08333333,  1261.5       ]])
```

UV-CDAT GUI

```
FAILED INIT
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/software/anaconda2/vistrails/vistrails/core/modules/vistrails_module.py", line 327, in update
    self.compute()
  File "/software/anaconda2/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 379, in compute
    self.var = self.to_python()
  File "/software/anaconda2/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 238, in to_python
    var = cdmsfile.__call__(varName, **kwargs)
  File "/software/anaconda2/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 33, in __call__
    return v(*args, **kwargs)
  File "/software/anaconda2/lib/python2.7/site-packages/cdms2/avariable.py", line 159, in __call__
    grid=grid)
  File "/software/anaconda2/lib/python2.7/site-packages/cdms2/selectors.py", line 176, in unmodified_select
    fetched = result.subRegion(*specifications)
  File "/software/anaconda2/lib/python2.7/site-packages/cdms2/avariable.py", line 717, in subRegion
    slicelist = self.reg_specs2slices (speclist)
  File "/software/anaconda2/lib/python2.7/site-packages/cdms2/avariable.py", line 1315, in reg_specs2slices
    raise CDMSError, OutOfRange + str(item)
CDMSError: Coordinate interval is out of range or intersection has no data: ('1973-05-31', '1973-05-31')
ERROR:root:Uncaught exception: "Coordinate interval is out of range or intersection has no data: ('1973-05-31', '1973-05-31')"
None
```

**Comment by doutriaux1** [comment]
because by defautl it looks as "con" look at the node and if the node is not EXACTLY that value it will fail. You want to read it with "cob" for a single value. Now the question is why does the GUI sends the bounds value and not the actual node value...

**Comment by doutriaux1** [comment]
@chaosphere2112 only assining this to you to make sure it works in the new gui. I think it's safe to close and say will not fix for vistrails.
