### ISSUE TITLE
vcs import error

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1914]
The latest build of uvcdat sees an error with import vcs. It appears in 
 f = open(os.path.join(vcs.prefix, "share", "vcs", "wmo_symbols.json"))
the prefix is incorrect. See below.
 
[mcenerney1ml:~/diagout] mcenerney1% python
Python 2.7.11 (default, Apr  6 2016, 10:18:59) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/uvcdat/04_06_16/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs-v2.5.0_267_g4bafc26-py2.7.egg/vcs/__init__.py", line 33, in <module>
    import Canvas  # noqa
  File "/usr/local/uvcdat/04_06_16/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs-v2.5.0_267_g4bafc26-py2.7.egg/vcs/Canvas.py", line 49, in <module>
    from VTKPlots import VTKVCSBackend
  File "/usr/local/uvcdat/04_06_16/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs-v2.5.0_267_g4bafc26-py2.7.egg/vcs/VTKPlots.py", line 5, in <module>
    import vcs2vtk
  File "/usr/local/uvcdat/04_06_16/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs-v2.5.0_267_g4bafc26-py2.7.egg/vcs/vcs2vtk.py", line 15, in <module>
    f = open(os.path.join(vcs.prefix, "share", "vcs", "wmo_symbols.json"))
IOError: [Errno 2] No such file or directory: '/usr/local/uvcdat/04_06_16/Library/Frameworks/Python.framework/Versions/2.7/share/vcs/wmo_symbols.json'

**Comment by doutriaux1** [comment]
fixed by cleanup_for_conda_and_setuptools #1908
