### ISSUE TITLE
udunits.dat

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1921]
```
[durack1@crunchy Density_bining]$ drive_density.py cmip5 piControl /work/durack1/Shared/150313_data_density True True
NAME: /usr/local/uvcdat/2016-03-09/lib/python2.7/site-packages/unidata/udunits.dat
Traceback (most recent call last):
  File ".//drive_density.py", line 23, in <module>
    from binDensity import densityBin
  File "/export/durack1/git/Density_bining/binDensity.py", line 37, in <module>
    from durolib import fixVarUnits,getGitInfo,globalAttWrite
  File "/export/durack1/git/pylib/durolib.py", line 30, in <module>
    import cdat_info,cdtime,code,datetime,errno,gc,inspect,os,pytz,re,string,sys,time
  File "build/bdist.linux-x86_64/egg/pytz/__init__.py", line 29, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3138, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3124, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 652, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 645, in __init__
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 701, in add_entry
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2139, in find_on_path
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2521, in from_location
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2835, in _reload_version
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2486, in _version_from_file
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2654, in _get_metadata
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2030, in get_metadata_lines
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2024, in get_metadata
IOError: [Errno 13] Permission denied: '/usr/local/uvcdat/2016-03-09/lib/python2.7/site-packages/pcmdi_metrics-1.0_142_ga64bd39-py2.7.egg-info'
```

**Comment by durack1** [comment]
Is the string `NAME: /usr/local/uvcdat/2016-03-09/lib/python2.7/site-packages/unidata/udunits.dat` some leftover print statement from some earlier testing? If so it should be a fairly trivial delete and close resolution for this issue

**Comment by doutriaux1** [comment]
yes it's gone from master, I guess it's one of the "benefits" form being a guinea-pig user.
