### ISSUE TITLE
conda uvcdat channel?

### ISSUE THREAD

**Issue by davidedelvento** [UV-CDAT/uvcdat#1940]
Is any of you guys responsible for the conda uvcdat channel https://anaconda.org/uvcdat/ or do you know who is?

The uvcdat download from there has several issues (some of which are #1935 #1936 and #1937 but there are more, some specific to conda) and I would like to report them.

**Comment by aashish24** [comment]
I believe so. @doutriaux1 has been working on conda recipes for some time. He will have some update on it.

**Comment by doutriaux1** [comment]
@davidedelvento the conda channel is a work in progress, as of today I'm planning on uploading our first official conda packages there. But still experimental. Whatever is there as I type this is most definitely garbage.

**Comment by doutriaux1** [comment]
@davidedelvento can I ping you once it's up and ready? I would love to get some feedback on this. Thanks.

**Comment by davidedelvento** [comment]
Sure, you can ping me when it's ready.

Note that despite you thinking what is there is garbage, I was able to successfully install that (with considerable effort) and it seems to be working, besides that when I open any of the examples it ask me to enable some remote packages which I don't seem able to do (but that is probably just my ignorance).

If it's useful, I can let you know the issues I've encountered and how I've worked around them (in this ticket or some better venue as you prefer) -- Cheers

**Comment by doutriaux1** [comment]
@davidedelvento mac and Linux should be ready to go for 2.4.1 now. Please let me know (gently 😉 ) which tweaks are necessary for you with this version. Thanks!

**Comment by doutriaux1** [comment]
`conda install uvcdat -c uvcdat`

**Comment by davidedelvento** [comment]
Great improvements! I've found only 3 issues:

1. the conda package does not delcare the pyopenssl dependency
2. responding "yes" to the `do you want to allow UV-CDAT to collect anonmymous usage information?` causes

```
/path/to/bin/uvcdat: line 64:  5122 Segmentation fault      (core dumped) python "/path/to/uvcdat/2.4.1/vistrails/vistrails/uvcdat.py" "$@" >> $target 2>&1
```

which of course continues forever until `~/.uvcdat` is purged

3. Opening the examples files causes errors like the following (this could be operator incapacity):

```
Critical message:

Pipeline has errors. Please see the detailed message for more information.

Missing package: edu.utah.sci.vistrails.vtk
Missing package: edu.utah.sci.vistrails.vtk
Missing package: edu.utah.sci.vistrails.vtk
Missing package: edu.utah.sci.vistrails.sudswebservices
Missing package: edu.utah.sci.vistrails.vtk
Missing package: edu.utah.sci.vistrails.vtk
Missing Requirement: suds

Time: 2016-04-21 20:20:49,282

Location: /path/to/uvcdat/2.4.1/vistrails/vistrails/gui/vistrail_controller.py, line 447
```

**Comment by doutriaux1** [comment]
That's great news I will update uvcdat/vistrails conda package to add the pyopenssl dependency, I wouldn't worry about the vistrails warnings, as I mentioned we are moving away from vistrails. 

I can't reproduce the seg fault, it might be due to the pyopenssl. Which OS are you running under?

**Comment by davidedelvento** [comment]
I was running under RHEL, don't remember which version (will check later and report) but I think the oldest still supported (not my choice).

I'll see if I can provide a corefile or at least a traceback for the core dump.

Last, but not least, I forgot to mention the GLIB 2.14 dependency (my OS had 2.12) which I solved by recompiling GLIB 2.14 (other versions of glib which I had around for other purposes did not seem to work). That's not a big deal for me, but it could be a showstopper for more naive users, so I suggest you put the strict version dependency into the conda package and change the uvcdat script to use that.

Cheers

**Comment by mcenerney1** [comment]
Getting an error running diagnostics

Traceback (most recent call last):
  File "/Users/mcenerney1/anaconda/lib/python2.7/site-packages/ESMP/src/ESMP_LoadESMF.py", line 126, in <module>
    _ESMF = _NP.ctypeslib.load_library('libesmf_fullylinked',libsdir)
  File "/Users/mcenerney1/anaconda/lib/python2.7/site-packages/numpy/ctypeslib.py", line 123, in load_library
    return ctypes.cdll[libpath]
  File "/Users/mcenerney1/anaconda/lib/python2.7/ctypes/__init__.py", line 440, in __getitem__
    return getattr(self, name)
  File "/Users/mcenerney1/anaconda/lib/python2.7/ctypes/__init__.py", line 435, in __getattr__
    dll = self._dlltype(name)
  File "/Users/mcenerney1/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/mcenerney1/anaconda/lib/libO/Darwin.gfortran.64.mpiuni.default/libesmf_fullylinked.dylib, 6): Library not loaded: /usr/local/lib/libgfortran.3.dylib
  Referenced from: /Users/mcenerney1/anaconda/lib/libO/Darwin.gfortran.64.mpiuni.default/libesmf_fullylinked.dylib
  Reason: image not found

**Comment by mcenerney1** [comment]
How do I run ctest in this environment?

**Comment by doutriaux1** [comment]
@mcenerney1 you didn't install the correct FOrtran on your Mac, see: https://github.com/UV-CDAT/uvcdat/wiki/Install-on-Mac-OS-X I will had this to the Anaconda page.

**Comment by davidedelvento** [comment]
For some obscure reasons, github does not allow me to attach the whole back trace, but anyway, here are the relevant issues:

1) The problem finally occurs in  0x00002ba52102a7ab in init_one_static_tls (map=0x25762a0) at allocatestack.c:1179

2) The last python which is touched before moving into C is vtk/vtkCommonCore.py

3) The last non-VTK python which is touched before invoking vtk is vcs/utils.py coming from vcs/__init__.py coming from uvcdat/mainwindow.py

Of course the core-dumping process knows nothing about python, so I don't have those line numbers.

This is RHEL 6.4 (you may try to reproduce it on a virtual machine with the comparable CentOS)

**Comment by doutriaux1** [comment]
that is odd. The linux64 conda packages are actually built on a RH 6.4 as well. I'm suspecting something to do with your (non-existing?) graphics card. @aashish24 @danlipsa you're the VTK expert any idea? 
Alo I did have the GLIB error originally when going from ubunutu to RH6. Hence the building on RH6. You may need/want to try a `sudo yum update`.

**Comment by davidedelvento** [comment]
I did run this on a node without graphic card, but why should that matter? Tomorrow I can give it a try on a different node which does have the graphic card and see if it is any different.

I don't have root on the system, so I can't run `yum update`. But as I said, that's a non-issue for me, since I rebuild GLIB and linked against it, which works just fine. I'm just suggesting that you use the nice conda feature of providing the exact dependencies you need for any program, and in this case it is GLIB, so even the most naive user can run it without a hassle.

**Comment by doutriaux1** [comment]
thanks @davidedelvento will most definitely add glib as a conda dependency. @aashish24 @danlipsa any hints for @davidedelvento as far as the VTK error goes?

**Comment by davidedelvento** [comment]
Ok, so let me summarize the still open issues for the new people nose'd.

- The segfault described at https://github.com/UV-CDAT/uvcdat/issues/1940#issuecomment-214525667 happens on a node with GPU too.  Let me know if you would like me to do additional tests about it. 

- The VTK errors described at https://github.com/UV-CDAT/uvcdat/issues/1940#issuecomment-213100951 are still there

Thanks.
