### ISSUE TITLE
numpy.NewAxis broken

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1974]
the follwoing used to work

```
f=cdms2.open("/usr/local/uvcdat/2.4.1/share/uvcdat/sample_data/clt.nc")
>>> s=f("clt",slice(0,1))
>>> s.shape
(1, 46, 72)
>>> s=f("clt",slice(0,1),squeeze=1)
>>> s.shape
(46, 72)
>>> import cdutil
>>> zm = cdutil.averager(s,axis="x")
>>> zm.shape
(46,)
>>> s2 = s -zm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda2/envs/uvcdat-2.4.1/lib/python2.7/site-packages/cdms2/avariable.py", line 1436, in __sub__
    return MV.subtract(self, other)
  File "/usr/local/anaconda2/envs/uvcdat-2.4.1/lib/python2.7/site-packages/cdms2/MV2.py", line 228, in __call__
    maresult = self.mafunc(ta,tb)
  File "/usr/local/anaconda2/envs/uvcdat-2.4.1/lib/python2.7/site-packages/numpy/ma/core.py", line 935, in __call__
    m = umath.logical_or(getmaskarray(a), mb)
ValueError: operands could not be broadcast together with shapes (46,72) (46,) 
>>> s2 = s -zm[:,numpy.newaxis]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda2/envs/uvcdat-2.4.1/lib/python2.7/site-packages/cdms2/avariable.py", line 1401, in __getitem__
    speclist = self._process_specs(key, {})
  File "/usr/local/anaconda2/envs/uvcdat-2.4.1/lib/python2.7/site-packages/cdms2/avariable.py", line 1169, in _process_specs
    raise CDMSError, 'Sorry, you cannot use NewAxis in this context ' + str(specs)
cdms2.error.CDMSError: Sorry, you cannot use NewAxis in this context (slice(None, None, None), None)
>>> s2 = s - zm[:,numpy.newaxis]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda2/envs/uvcdat-2.4.1/lib/python2.7/site-packages/cdms2/avariable.py", line 1401, in __getitem__
    speclist = self._process_specs(key, {})
  File "/usr/local/anaconda2/envs/uvcdat-2.4.1/lib/python2.7/site-packages/cdms2/avariable.py", line 1169, in _process_specs
    raise CDMSError, 'Sorry, you cannot use NewAxis in this context ' + str(specs)
cdms2.error.CDMSError: Sorry, you cannot use NewAxis in this context (slice(None, None, None), None)
```

**Comment by doutriaux1** [comment]
for now a wrork around:

```
>>> s,zm  = genutil.grower(s,zm)
>>> s.shape
(46, 72)
>>> zm.shape
(46, 72)
```

**Comment by doutriaux1** [comment]
@lee1043 thanks for reporting this bug

**Comment by doutriaux1** [comment]
maybe 3.0 target?

**Comment by dnadeau4** [comment]
```python
import MV2
import numpy
 b=MV2.ones((10,12))
a=b[0]
c=b+a[numpy.newaxis,:]
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/anaconda2/envs/numpy1_11/lib/python2.7/site-packages/cdms2/avariable.py", line 1413, in __getitem__
    speclist = self._process_specs(key, {})
  File "/software/anaconda2/envs/numpy1_11/lib/python2.7/site-packages/cdms2/avariable.py", line 1181, in _process_specs
    raise CDMSError, 'Sorry, you cannot use NewAxis in this context ' + str(specs)
cdms2.error.CDMSError: Sorry, you cannot use NewAxis in this context (None, slice(None, None, None))
c=b.asma()+a.asma()[numpy.newaxis,:]

**Comment by dnadeau4** [comment]
This issue was moved to UV-CDAT/cdms#6
