### ISSUE TITLE
cdms2: Error on file that works fine with other netcdf readers.

### ISSUE THREAD

**Issue by cpaulik** [UV-CDAT/uvcdat#2034]
The netcdf file in [g2_BIOPAR_SWI-TS_201001310000_C0243_ASCAT_V1.0.0.zip](https://github.com/UV-CDAT/uvcdat/files/329538/g2_BIOPAR_SWI-TS_201001310000_C0243_ASCAT_V1.0.0.zip) can not be opened using cdms2, but it works fine with `netcdf4-python`, `panoply` or `gdal`. 

I first stumbled onto this error when using the cf-checker and have already reported the problem to @RosalynHatcher .

See this code snippet for an example and below the conda environment I used for testing this.

```python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import netCDF4 as nc4
>>> import cdms2
>>> f = cdms2.open("g2_BIOPAR_SWI-TS_201001310000_C0243_ASCAT_V1.0.0.nc", "r")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/cdms-test/lib/python2.7/site-packages/cdms2/dataset.py", line 309, in openDataset
    file1 = CdmsFile(path,"r")
  File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/cdms-test/lib/python2.7/site-packages/cdms2/dataset.py", line 1001, in __init__
    self.attributes[att]=self._file_.__dict__[att]
  File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/cdms-test/lib/python2.7/site-packages/cdms2/cdmsobj.py", line 452, in _listatts
    for nm,val in self.__dict__.items():
ValueError: data type must provide an itemsize
>>> ds = nc4.Dataset("g2_BIOPAR_SWI-TS_201001310000_C0243_ASCAT_V1.0.0.nc")
>>> ds
<type 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format UNDEFINED):
    producer: tuwien
    product_version: V1.0.0
    long_name: Soil Water Index
    processing_mode: Consolidated
    references: http://land.copernicus.eu/global/products/swi
    id: g2_BIOPAR_SWI-TS_201001310000_C0243_ASCAT_V1.0.0.nc
    geospatial_lat_max: 2.487
    copyright: Copyright Copernicus Global Land Service, 2015. Produced by Technische Universität Wien (TU Wien), Austria. Distributed by VITO NV, Belgium.
    title: Copernicus Global Land Service Soil Water Index Time Series (SWI_TS)
    platform: METOP
    archive_facility: VITO
    sensor: ASCAT
    processing_level: L3
    orbit_type: LEO
    featureType: timeSeries
    geospatial_lat_min: 0.0
    time_coverage_start: 2010-01-01T00:00:00
    institution: TU Wien
    geospatial_lon_max: -47.7229
    geospatial_lon_min: -49.9967
    parent_identifier: urn:cgls:tiles:swits_v1_12.5km
    time_coverage_end: 2010-01-31T00:00:00
    Conventions: CF-1.6
    source: ASCAT on board MetOP
    date_created: 2016-06-22 16:38:22
    identifier: urn:cgls:tiles:swits_v1_12.5km:SWI-TS_201001310000_C0243_ASCAT_V1.0.0
    dataset_name: SWI time series for cell 0243
    history: 2016-06-22 -- Product creation by swi_ts processor version 0.6.3.post.dev6.pre
    dimensions(sizes): locations(196), time(31)
    variables(dimensions): float64 lon(locations), float64 lat(locations), float64 alt(locations), int64 location_id(locations), <type 'str'> location_description(locations), float64 time(time), uint8 SWI_005(locations,time), uint8 SWI_010(locations,time), uint8 SWI_020(locations,time), uint8 SWI_001(locations,time), uint8 SWI_015(locations,time), uint8 QFLAG_040(locations,time), uint8 SWI_100(locations,time), uint8 QFLAG_010(locations,time), uint8 SWI_040(locations,time), uint8 QFLAG_015(locations,time), uint8 QFLAG_100(locations,time), uint8 SWI_060(locations,time), uint8 QFLAG_020(locations,time), uint8 QFLAG_005(locations,time), uint8 SSF(locations,time), uint8 QFLAG_001(locations,time), uint8 QFLAG_060(locations,time)
    groups: 

>>> ds.variables['SWI_060'][:]
masked_array(data =
 [[-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]
 ..., 
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]],
             mask =
 [[ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 ..., 
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]],
       fill_value = 255)
```

### conda

```
cdat-info                 0.0.0                     <pip>
cdat_info                 2.4.1                    UVCDAT    uvcdat
cdms                      1.0                       <pip>
cdms2                     2.4.1                    UVCDAT    uvcdat
cdtime                    2.4.1                    UVCDAT    uvcdat
clapack                   3.2.1                    UVCDAT    uvcdat
curl                      7.49.0                        0    defaults
distarray                 2.4.1                    UVCDAT    uvcdat
esmf                      ESMF_6_3_0rp1_ESMP_01          UVCDAT    uvcdat
g2clib                    1.4.0b                   UVCDAT    uvcdat
hdf5                      1.8.16                        0    defaults
jasper                    1.900.1                  UVCDAT    uvcdat
jbig                      2.1                           0    defaults
jpeg                      8d                            0    defaults
lapack                    3.4.2                    UVCDAT    uvcdat
libcdms                   2.4.1                    UVCDAT    uvcdat
libcf                     1.0.beta11               UVCDAT    uvcdat
libgfortran               3.0.0                         1    defaults
libnetcdf                 4.3.3.1                  UVCDAT    uvcdat
libpng                    1.6.22                        0    defaults
libtiff                   4.0.6                         2    defaults
ma                        1.0                       <pip>
mv                        1.0                       <pip>
mv2                       1.0                       <pip>
netcdf4                   1.2.4                     <pip>
numpy                     1.9.2                    py27_2    defaults
openblas                  0.2.14                        4    defaults
openssl                   1.0.2h                        1    defaults
ossuuid                   1.6.2                    UVCDAT    uvcdat
pip                       8.1.2                    py27_0    defaults
python                    2.7.11                        0    defaults
readline                  6.2                           2    defaults
regrid                    1.0                       <pip>
regrid2                   2.4.1                    UVCDAT    uvcdat
setuptools                23.0.0                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py27_0    defaults
xz                        5.2.2                         0    defaults
zlib                      1.2.8                         3    defaults
```

**Comment by cpaulik** [comment]
Debugging the problem let me to https://github.com/UV-CDAT/uvcdat/blob/master/Packages/cdms2/Lib/dataset.py#L1095 where the C library is called.

**Comment by dnadeau4** [comment]
@cpaulik  This is in cdunif module.  It is old and does not understand all the types that are in your file.  (ubyte, string, int64).
