### ISSUE TITLE
genutil broken in nightly

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#2035]
```
(uvcdatNightly)durack1@oceanonly:[150219_AMIPForcingData]:[864]> python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Jun 15 2016, 15:21:30) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import genutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/durack1/anaconda2/envs/uvcdatNightly/lib/python2.7/site-packages/genutil/__init__.py", line 5, in <module>
    from grower import grower
  File "/export/durack1/anaconda2/envs/uvcdatNightly/lib/python2.7/site-packages/genutil/grower.py", line 4, in <module>
    import cdms2 as cdms
  File "/export/durack1/anaconda2/envs/uvcdatNightly/lib/python2.7/site-packages/cdms2/__init__.py", line 30, in <module>
    from .dataset import createDataset, openDataset, useNetcdf3, \
  File "/export/durack1/anaconda2/envs/uvcdatNightly/lib/python2.7/site-packages/cdms2/dataset.py", line 17, in <module>
    from .CDMLParser import CDMLParser
  File "/export/durack1/anaconda2/envs/uvcdatNightly/lib/python2.7/site-packages/cdms2/CDMLParser.py", line 5, in <module>
    from .cdxmllib import XMLParser
  File "/export/durack1/anaconda2/envs/uvcdatNightly/lib/python2.7/site-packages/cdms2/cdxmllib.py", line 73, in <module>
    attrtrans = string.maketrans(' \r\n\t', '    ')
NameError: name 'string' is not defined
>>> import cdat_info
>>> cdat_info.version()
['v2', '5', '0', '572', 'ga06818f']
```

**Comment by doutriaux1** [comment]
fixed by #e31e2fd861ba1de60e36f692affb3847deb54359

**Comment by durack1** [comment]
@doutriaux1 great, when will conda be updated with this change - on the stroke of midnight tonight?

**Comment by doutriaux1** [comment]
you wished, that cronjob is not working. Will push one soon though I will let you know.
