### ISSUE TITLE
cdms2 broken in UV-CDAT 2.6.1

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#2107]
I've just installed a subset of the UV-CDAT tools from conda, following:
```
$ conda create -n uvcdat26slim -c uvcdat vcs cdms2 cdutil genutil vcsaddons eztemplate ipython spyder
```
When I go to load `cdms2` I get the following error:
```
duro@ocean:[MalteMeinshausen_GHGConcentrations]:[1881]> source activate uvcdat261slim
(uvcdat261slim) duro@ocean:[MalteMeinshausen_GHGConcentrations]:[1879]> which python
/export/duro/anaconda2/envs/uvcdat261slim/bin/python
(uvcdat261slim) duro@ocean:[MalteMeinshausen_GHGConcentrations]:[1865]> python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cdms2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/duro/anaconda2/envs/uvcdat261slim/lib/python2.7/site-packages/cdms2/__init__.py", line 30, in <module>
    from dataset import createDataset, openDataset, useNetcdf3, \
  File "/export/duro/anaconda2/envs/uvcdat261slim/lib/python2.7/site-packages/cdms2/dataset.py", line 6, in <module>
    import Cdunif
ImportError: /export/duro/anaconda2/envs/uvcdat261slim/lib/python2.7/site-packages/cdms2/Cdunif.so: undefined symbol: Getname
```

**Comment by dnadeau4** [comment]
@durack1 I think you might have the wrong cdms2 package.  Sometimes anaconda use the one that is already downloaded and sits in your cache.   Make sure you start with a clean slate using `conda clean --all` and answer yes to all questions.  

I tried your command and it worked on my ubuntu machine.   What linux operating system(OS)  are your working on?  `cat /etc/*release*`

**Comment by durack1** [comment]
@dnadeau4 
```
[duro@ocean ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
```

**Comment by doutriaux1** [comment]
@durack1 did you try @dnadeau4 suggestion?

**Comment by durack1** [comment]
@doutriaux1 I'll give it a go today.. Hit too many bumps at once yesterday so dropped this update from the to do list.. I'll report my experience once it's done

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 yep tried `conda clean --all` (twice actually) and I still get the same error, so the steps are:
```
[duro@ocean ~]$ conda clean --all
...
[duro@ocean ~]$ conda create -n uvcdat26slim -c uvcdat vcs cdms2 cdutil genutil vcsaddons eztemplate ipython spyder
...
```
and then:
```
duro@ocean:[~]:[2042]> source activate uvcdat26slim
(uvcdat26slim) duro@ocean:[~]:[2043]> which python
/export/duro/anaconda2/envs/uvcdat26slim/bin/python
(uvcdat26slim) duro@ocean:[~]:[2028]> python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cdms2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/duro/anaconda2/envs/uvcdat26slim/lib/python2.7/site-packages/cdms2/__init__.py", line 30, in <module>
    from dataset import createDataset, openDataset, useNetcdf3, \
  File "/export/duro/anaconda2/envs/uvcdat26slim/lib/python2.7/site-packages/cdms2/dataset.py", line 6, in <module>
    import Cdunif
ImportError: /export/duro/anaconda2/envs/uvcdat26slim/lib/python2.7/site-packages/cdms2/Cdunif.so: undefined symbol: Getname
>>>
```

**Comment by doutriaux1** [comment]
@durack1 can you post the result of
```
conda list
```
Also are you in bash?

**Comment by durack1** [comment]
@doutriaux1 here you go, and nope I'm running `conda` in `tcsh`:
```
[duro@ocean ~]$ conda list                                                                                         
# packages in environment at /export/duro/anaconda2:                                                                   
#                                                                                                                         
alabaster                 0.7.7                    py27_0                                                                 
anaconda-client           1.4.0                    py27_0                                                                 
anaconda                  custom                   py27_0                                                                 
anaconda-navigator        1.1.0                    py27_0                                                                 
argcomplete               1.0.0                    py27_1                                                                 
astropy                   1.1.2               np110py27_0                                                                 
babel                     2.2.0                    py27_0                                                                 
backports_abc             0.4                      py27_0                                                                 
beautifulsoup4            4.4.1                    py27_0                                                                 
bitarray                  0.8.1                    py27_0                                                                 
blaze                     0.9.1                    py27_0                                                                 
bokeh                     0.11.1                   py27_0                                                                 
boto                      2.39.0                   py27_0                                                                 
bottleneck                1.0.0               np110py27_0                                                                 
cairo                     1.12.18                       6                                                                 
cdecimal                  2.3                      py27_0                                                                 
cffi                      1.5.2                    py27_0                                                                 
chest                     0.2.3                    py27_0                                                                 
cloudpickle               0.1.1                    py27_0                                                                 
clyent                    1.2.1                    py27_0                                                                 
colorama                  0.3.7                    py27_0                                                                 
conda-build               1.20.0                   py27_0                                                                 
conda                     4.2.3                    py27_0    conda-canary                                                 
conda-env                 2.6.0                         0    conda-canary                                                 
conda-manager             0.3.1                    py27_0                                                                 
configobj                 5.0.6                    py27_0                                                                 
cryptography              1.3                      py27_0                                                                 
curl                      7.45.0                        0                                                                 
cycler                    0.10.0                   py27_0                                                                 
cython                    0.23.4                   py27_0                                                                 
cytoolz                   0.7.5                    py27_0                                                                 
dask                      0.8.1                    py27_0                                                                 
datashape                 0.5.1                    py27_0                                                                 
decorator                 4.0.9                    py27_0                                                                 
dill                      0.2.4                    py27_0                                                                 
docutils                  0.12                     py27_0                                                                 
durolib                   1.0                       <pip>                                                                 
dynd-python               0.7.2                    py27_0                                                                 
enum34                    1.1.2                    py27_0                                                                 
et_xmlfile                1.0.1                    py27_0                                                                 
fastcache                 1.0.2                    py27_0                                                                 
flask                     0.10.1                   py27_1                                                                 
flask-cors                2.1.2                    py27_0                                                                 
fontconfig                2.11.1                        5                                                                 
freetype                  2.5.5                         0                                                                 
funcsigs                  0.4                      py27_0                                                                 
futures                   3.0.3                    py27_0                                                                 
gevent                    1.1.0                    py27_0                                                                 
greenlet                  0.4.9                    py27_0                                                                 
grin                      1.2.1                    py27_1                                                                 
h5py                      2.5.0               np110py27_4                                                                 
hdf5                      1.8.15.1                      2                                                                 
heapdict                  1.0.0                    py27_0                                                                 
idna                      2.0                      py27_0                                                                 
ipaddress                 1.0.14                   py27_0                                                                 
ipykernel                 4.3.1                    py27_0                                                                 
ipython                   4.1.2                    py27_1                                                                 
ipython_genutils          0.1.0                    py27_0                                                                 
ipywidgets                4.1.1                    py27_0                                                                 
itsdangerous              0.24                     py27_0                                                                 
jbig                      2.1                           0                                                                 
jdcal                     1.2                      py27_0                                                                 
jedi                      0.9.0                    py27_0                                                                 
jinja2                    2.8                      py27_0                                                                 
jpeg                      8d                            0                                                                 
jsonschema                2.4.0                    py27_0                                                                 
jupyter                   1.0.0                    py27_2                                                                 
jupyter_client            4.2.2                    py27_0                                                                 
jupyter_console           4.1.1                    py27_0                                                                 
jupyter_core              4.1.0                    py27_0                                                                 
libdynd                   0.7.2                         0                                                                 
libffi                    3.0.13                        0                                                                 
libgfortran               3.0                           0                                                                 
libpng                    1.6.17                        0                                                                 
libsodium                 1.0.3                         0                                                                 
libtiff                   4.0.6                         1                                                                 
libxml2                   2.9.2                         0                                                                 
libxslt                   1.1.28                        0                                                                 
llvmlite                  0.9.0                    py27_0                                                                 
locket                    0.2.0                    py27_0                                                                 
lxml                      3.6.0                    py27_0                                                                 
markupsafe                0.23                     py27_0                                                                 
matplotlib                1.5.1               np110py27_0                                                                 
mistune                   0.7.2                    py27_0                                                                 
mkl                       11.3.1                        0                                                                 
mkl-service               1.1.2                    py27_0                                                                 
mpmath                    0.19                     py27_0                                                                 
multipledispatch          0.4.8                    py27_0                                                                 
nbconvert                 4.1.0                    py27_0                                                                 
nbformat                  4.0.1                    py27_0                                                                 
networkx                  1.11                     py27_0                                                                 
nltk                      3.2                      py27_0                                                                 
nose                      1.3.7                    py27_0                                                                 
notebook                  4.1.0                    py27_1                                                                 
numba                     0.24.0              np110py27_0                                                                 
numexpr                   2.5                 np110py27_0                                                                 
numpy                     1.10.4                   py27_1                                                                 
odo                       0.4.2                    py27_0                                                                 
openpyxl                  2.3.2                    py27_0                                                                 
openssl                   1.0.2g                        0                                                                 
pandas                    0.18.0              np110py27_0                                                                 
partd                     0.3.2                    py27_1                                                                 
patchelf                  0.8                           0                                                                 
path.py                   8.1.2                    py27_1                                                                 
patsy                     0.4.0               np110py27_0                                                                 
pep8                      1.7.0                    py27_0                                                                 
pexpect                   4.0.1                    py27_0                                                                 
pickleshare               0.5                      py27_0                                                                 
pillow                    3.1.1                    py27_0                                                                 
pip                       8.1.1                    py27_1                                                                 
pixman                    0.32.6                        0                                                                 
ply                       3.8                      py27_0                                                                 
psutil                    4.1.0                    py27_0                                                                 
ptyprocess                0.5                      py27_0                                                                 
py                        1.4.31                   py27_0                                                                 
pyasn1                    0.1.9                    py27_0                                                                 
pycairo                   1.10.0                   py27_0                                                                 
pycosat                   0.6.1                    py27_0                                                                 
pycparser                 2.14                     py27_0                                                                 
pycrypto                  2.6.1                    py27_0
pycurl                    7.19.5.3                 py27_0
pyflakes                  1.1.0                    py27_0
pygments                  2.1.1                    py27_0
pyopenssl                 0.15.1                   py27_2
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.4                   py27_1
pytables                  3.2.2               np110py27_1
pytest                    2.8.5                    py27_0
python                    2.7.12                        1
python-dateutil           2.5.1                    py27_0
pytz                      2016.2                   py27_0
pyyaml                    3.11                     py27_1
pyzmq                     15.2.0                   py27_0
qt                        4.8.7                         1
qtawesome                 0.3.2                    py27_0
qtconsole                 4.2.0                    py27_0
qtpy                      1.0                      py27_0
readline                  6.2                           2
redis                     2.6.9                         0
redis-py                  2.10.3                   py27_0
requests                  2.9.1                    py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_0
scikit-image              0.12.3              np110py27_0
scikit-learn              0.17.1              np110py27_0
scipy                     0.17.0              np110py27_2
setuptools                20.3                     py27_0
simplegeneric             0.8.1                    py27_0
singledispatch            3.4.0.3                  py27_0
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.3.5                    py27_0
sphinx_rtd_theme          0.1.9                    py27_0
spyder                    2.3.8                    py27_1
sqlalchemy                1.0.12                   py27_0
sqlite                    3.13.0                        0
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1               np110py27_0
sympy                     1.0                      py27_0
terminado                 0.5                      py27_1
tk                        8.5.18                        0
toolz                     0.7.4                    py27_0
tornado                   4.3                      py27_0
traitlets                 4.2.1                    py27_0
unicodecsv                0.14.1                   py27_0
util-linux                2.21                          0
werkzeug                  0.11.4                   py27_0
wheel                     0.29.0                   py27_0
xlrd                      0.9.4                    py27_0
xlsxwriter                0.8.4                    py27_0
xlwt                      1.0.0                    py27_0
xz                        5.0.5                         1
yaml                      0.1.6                         0
zeromq                    4.1.3                         0
zlib                      1.2.8                         0
[duro@ocean ~]$
```

**Comment by dnadeau4** [comment]
@durack1 there is no cdms2 in your list.  I just tried to create your env on Ubuntu and worked fine.  It seems that you have numpy 1.10 installed on your machine.  Make sure your activate your environment.

**Comment by durack1** [comment]
@dnadeau4 is there a reason why:
```
[duro@ocean ~]$ conda create -n uvcdat26slim -c uvcdat vcs cdms2 cdutil genutil vcsaddons eztemplate ipython spyder
```
Is failing then?

**Comment by dnadeau4** [comment]
Did you ran `source activate uvcdat26slim`?

**Comment by durack1** [comment]
@dnadeau4 yep, see the second block [above](https://github.com/UV-CDAT/uvcdat/issues/2107#issuecomment-242454616)

**Comment by durack1** [comment]
@dnadeau4 it looks like this was due to a broken `conda`/`Anaconda` install - the hard-coded install paths were changed since it was first installed, a migration across hardware.. Closing..
