### ISSUE TITLE
Extract monthly mean from daily mean with cdutil.ANNUALCYCLE

### ISSUE THREAD

**Issue by lee1043** [UV-CDAT/uvcdat#2142]
I am having trouble with extracting monthly mean from daily mean dataset. I have applied cdutil's ANNUALCYCLE function but it returns error as below.  I suspect maybe because time dimension is not recognizable, but not sure. @doutriaux1 @dnadeau4 Do you have any idea?

data: [ftp://ftp.cdc.noaa.gov/Datasets/20thC_ReanV2/Dailies/monolevel/prmsl.1871.nc](ftp://ftp.cdc.noaa.gov/Datasets/20thC_ReanV2/Dailies/monolevel/prmsl.1871.nc)

script: test.py (below)

```
import cdms2 as cdms
import cdutil

f = cdms.open('prmsl.1871.nc')
d = f('prmsl')
d_ann = cdutil.ANNUALCYCLE(d)
```

Error:
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    d_ann = cdutil.ANNUALCYCLE(d)
  File "/export_backup/lee1043/anaconda2/lib/python2.7/site-packages/cdutil/times.py", line 1286, in get
    s.append(TimeSlicer.get(self,slab,season,criteriaarg,statusbar=statusbar,sum=sum))
  File "/export_backup/lee1043/anaconda2/lib/python2.7/site-packages/cdutil/times.py", line 383, in get
    slices,bounds,norm=self.slicer(tim,slicerarg)
  File "/export_backup/lee1043/anaconda2/lib/python2.7/site-packages/cdutil/times.py", line 631, in monthBasedSlicer
    b0=cdtime.reltime(bnds[i][0],units)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

NetCDF attributes:
```
netcdf prmsl.1871 {
dimensions:
	lon = 180 ;
	nbnds = 2 ;
	lat = 91 ;
	time = UNLIMITED ; // (365 currently)
variables:
	float lat(lat) ;
		lat:units = "degrees_north" ;
		lat:actual_range = 90.f, -90.f ;
		lat:long_name = "Latitude" ;
		lat:standard_name = "latitude" ;
		lat:axis = "Y" ;
		lat:coordinate_defines = "point" ;
	float lon(lon) ;
		lon:units = "degrees_east" ;
		lon:long_name = "Longitude" ;
		lon:actual_range = 0.f, 358.f ;
		lon:standard_name = "longitude" ;
		lon:axis = "X" ;
		lon:coordinate_defines = "point" ;
	double time_bnds(time, nbnds) ;
		time_bnds:long_name = "Time Boundaries" ;
	double time(time) ;
		time:avg_period = "0000-00-01 00:00:00" ;
		time:units = "hours since 1800-1-1 00:00:0.0" ;
		time:long_name = "Time" ;
		time:delta_t = "0000-00-01 00:00:00" ;
		time:standard_name = "time" ;
		time:axis = "T" ;
		time:coordinate_defines = "start" ;
		time:actual_range = 622368., 631104. ;
	float prmsl(time, lat, lon) ;
		prmsl:cell_methods = "time: mean (of each 6-hourly interval) mean (of 4 6-hourly means)" ;
		prmsl:long_name = "Daily Pressure at Mean Sea Level" ;
		prmsl:units = "Pa" ;
		prmsl:precision = 1s ;
		prmsl:GRIB_id = 2s ;
		prmsl:GRIB_name = "PRMSL" ;
		prmsl:var_desc = "Mean Sea Level Pressure" ;
		prmsl:dataset = "NOAA-CIRES 20th Century Reanalysis version 2 Daily Averages" ;
		prmsl:level_desc = "Mean Sea Level" ;
		prmsl:statistic = "Ensemble Mean" ;
		prmsl:parent_stat = "Individual Obs" ;
		prmsl:standard_name = "air_pressure_at_sea_level" ;
		prmsl:missing_value = -9.96921e+36f ;
		prmsl:actual_range = 95766.f, 104723.f ;
		prmsl:valid_range = 77000.f, 125000.f ;
		prmsl:statistic_method = "Ensemble mean is calculated by averaging over all 56 ensemble members at each time step and then averaging mean over all time steps in a day" ;

// global attributes:
		:Conventions = "CF-1.2" ;
		:title = "Daily NOAA-CIRES 20th Century Reanalysis" ;
		:comments = "Data is from \n",
			"NOAA-CIRES 20th Century Reanalysis version 2\n",
			"(4x/day).  It consists of most variables interpolated to\n",
			"pressure surfaces from model (sigma) surfaces." ;
		:platform = "Model" ;
		:institution = "NOAA ESRL/PSD" ;
		:citation = "Compo,G.P. <http://www.esrl.noaa.gov/psd/people/gilbert.p.compo>, \n",
			"J.S. Whitaker <http://www.esrl.noaa.gov/psd/people/jeffrey.s.whitaker>,\n",
			" and P.D. Sardeshmukh, 2006: Feasibility of a 100 year reanalysis using\n",
			" only surface pressure data.\n",
			" <http://www.esrl.noaa.gov/psd/people/gilbert.p.compo/Compoetal2006.pdf>\n",
			" /Bull. Amer. Met. Soc./, 87, 175-190." ;
		:version = "2.0" ;
		:history = "created 2010/05 by Hoop (netCDF3)\n",
			"Converted to chunked, deflated non-packed NetCDF4 2014/05" ;
		:References = "http://www.esrl.noaa.gov/psd/data/gridded/data.20thCentReanalysisV2.html" ;
		:dataset_title = "NOAA-CIRES 20th Century Reanalysis (V2)" ;
```

**Comment by lee1043** [comment]
Problem solved by using `cdutil.setTimeBoundsDaily(d, 1 )`

**Comment by gleckler1** [comment]
@lee1043 @doutriaux1 I am trying to use cdutil.JAN(dailyData) to extract a time series of repeating Januaries at daily time scale... not getting an error msg... I think its producing month means of each January, but what I really want are the daily values.   Anybody got any hints??

**Comment by doutriaux1** [comment]
@gleckler1 I will look at cdutil.JAN, it does extract all the values for january. Unfortunately it will also average them together, which you do not want. I'll try to isolate the function.

**Comment by doutriaux1** [comment]
found it!
```python
def monthBasedSlicer(tim, arg=None):
    """
    slicer function for the TimeSlicer class
    select months
    Author : Charles Doutriaux, doutriaux1@llnl.gov
    Original Date: April 2001
    Last Modified: October, 2001
    Input:
    :param tim: time axis
    :param arg: character string representing the desired month/season or integer(s)
             also you can pass a list of the months you want (string or integer)
             you can mix integer and strings
    Output:
```

Not even 20 years ago....

**Comment by doutriaux1** [comment]
voila:
```python
#!/usr/bin/env python
from __future__ import print_function
import cdutil
import cdms2
import numpy
import MV2

# C reate fake daily values
# more than two years
# Purposely not starting on janary 1st
# Purposely ending in middle of a january
raw = numpy.arange(19,780).tolist()
#  Purposely removing 2 days in janary
raw.pop(25)
raw.pop(25)
a = cdms2.createAxis(raw)
a.id = 'time'
a.units = 'days since 2016-11-25'
a.designateTime()
cdutil.setTimeBoundsDaily(a)
tc = a.asComponentTime()
print("Notice jan 8 and 9 are missing")
print(tc[16:30])
b = MV2.ones(a.shape)
b.setAxis(0,a)

# get actual indices, bounds for each set of indicds and len+start of each month
indices, bounds, starts = cdutil.monthBasedSlicer(a, ['jan',])


# For example here retrieve and concatenate all januaries together
jan = None
for i, sub in enumerate(indices):
    tmp = b(time=slice(sub[0],sub[-1]+1))
    print("Year",i,"shape of januaries",tmp.shape)
    if jan is None:
        jan = tmp
    else:
        jan = MV2.concatenate((jan, tmp))
print("Done:", jan.shape)
```
