### ISSUE TITLE
conda remove error (when removing a clone of 2.10)

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#2190]
@doutriaux1 I got the following error messages when trying to uninstall cleanly the 2.10 version I cloned yesterday before adding openmpi for my tests. Is this pcmdi stuff?

Note that I get the error messages, but my cdatmpi is gone from the `envs/` directory after I execute `conda remove`

```
bash-4.2$ conda remove -n cdatmpi --all

Package plan for package removal in environment /home/share/unix_files/cdat/miniconda2/envs/cdatmpi:

The following packages will be REMOVED:

    alabaster:                          0.7.10-py27_0      conda-forge
    asciidata:                          2.10-np112py27_0   uvcdat     
    asn1crypto:                         0.22.0-py27_0      conda-forge
[...]
    xz:                                 5.2.2-0            conda-forge
    zeromq:                             4.2.1-1            conda-forge
    zlib:                               1.2.11-0           conda-forge
    zonalmeans:                         2.10-np112py27_0   uvcdat     

Proceed ([y]/n)? y

+ /home/share/unix_files/cdat/miniconda2/envs/cdatmpi/bin/jupyter-nbextension disable nb_conda --py --sys-prefix
Traceback (most recent call last):
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatmpi/bin/jupyter-nbextension", line 4, in <module>
    import notebook.nbextensions
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatmpi/lib/python2.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatmpi/lib/python2.7/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named jupyter_core.paths
+ /home/share/unix_files/cdat/miniconda2/envs/cdatmpi/bin/jupyter-serverextension disable nb_conda --py --sys-prefix
Traceback (most recent call last):
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatmpi/bin/jupyter-serverextension", line 4, in <module>
    import notebook.serverextensions
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatmpi/lib/python2.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatmpi/lib/python2.7/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named jupyter_core.paths

WARNING conda.core.link:run_script(510): pre-unlink script failed for package conda-forge::nb_conda-2.2.0-py27_0
consider notifying the package maintainer
+ /home/share/unix_files/cdat/miniconda2/envs/cdatmpi/bin/python -m nb_conda_kernels.install --disable --prefix=/home/share/unix_files/cdat/miniconda2/envs/cdatmpi
/home/share/unix_files/cdat/miniconda2/envs/cdatmpi/bin/python: No module named enum

WARNING conda.core.link:run_script(510): pre-unlink script failed for package conda-forge::nb_conda_kernels-2.1.0-py27_0
consider notifying the package maintainer
WARNING conda.core.link:run_script(510): pre-unlink script failed for package conda-forge::widgetsnbextension-2.0.0-py27_0
consider notifying the package maintainer
```

**Comment by doutriaux1** [comment]
@jypeter well... uvcdat does bring jupyter in as a convenience thing, but that error message is jupyter related, i'd post an issue there.
