### ISSUE TITLE
Can't install uvcdat

### ISSUE THREAD

**Issue by yyplanton** [UV-CDAT/uvcdat#2194]
Hi,
I tried to install uvcdat on a server where I'm usually postprocess CMIP5 data.
One problem is that the conda version installed on the server is old... so I can't install uvcdat (MEMORY ERROR).
So I tried to install using miniconda:
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
And use it to install uvcdat: miniconda/bin/conda create -n myuvcdat uvcdat -c conda-forge -c uvcdat
It works. But I can't use uvcdat!

Python 2.7.14 | packaged by conda-forge | (default, Nov  4 2017, 10:15:28) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yplanton/miniconda/envs/myuvcdat/lib/python2.7/site-packages/vcs/__init__.py", line 92, in <module>
    from utils import *  # noqa
  File "/home/yplanton/miniconda/envs/myuvcdat/lib/python2.7/site-packages/vcs/utils.py", line 16, in <module>
    import cdtime
ImportError: libnetcdf.so.11: cannot open shared object file: No such file or directory

Is this problem known? Someone knows how to solve it?
Thanks.
Yann

**Comment by doutriaux1** [comment]
Netcdf has just been updated! I think that is your issue
try:
```
conda install libntcdf=4.4.1.1 -c conda-forge -c uvcdat
```

Let me know if this helps, if it does I will update the doc.

C.

**Comment by yyplanton** [comment]
It's working!
Thank you very much Charles.

Yann

**Comment by stefraynaud** [comment]
@doutriaux1, how to use this recommendation to fix the following installation errors?
Two cases. First one:
```
$> wget https://raw.githubusercontent.com/UV-CDAT/uvcdat/master/conda/2.12.yml
$> conda env create -f 2.12.yml
Fetching package metadata .................
ResolvePackageNotFound:
  - libnetcdf 4.4.1.1 5
```
Second one:
```
$> conda create -n test -y -c conda-forge -c uvcdat -c defaults --override-channels libnetcdf=4.4.1.1 uvcdat
$> source activate test
$> python -c 'import cdms2'
raynaud@apf2014003:~/Téléchargement>source activate test
(test) raynaud@apf2014003:~/Téléchargement>python -c 'import cdms2'
Traceback (most recent call last):
  File "/local/tmp/raynaud/minicondatestmy/envs/test/lib/python2.7/site-packages/ESMF/interface/loadESMF.py", line 122, in <module>
    mode=ct.RTLD_GLOBAL)
  File "/local/tmp/raynaud/minicondatestmy/envs/test/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libhdf5_hl.so.100: cannot open shared object file: No such file or directory
```

As with @yyplanton, these tests were performed on a fresh miniconda.

**Comment by doutriaux1** [comment]
@stefraynaud I would edit the yml directly. Are you on Linux? Which flavor. I will try to make sure the yml gets updated to still work.

**Comment by stefraynaud** [comment]
Yep, on linux.

**Comment by doutriaux1** [comment]
rh or ubuntu?

**Comment by stefraynaud** [comment]
CentOS 6! 
Yes, it's possible...

**Comment by bonnland** [comment]
Here are notes on my saga of trying to install uvcdat on a CentOS 7.4 vagrant machine.   I tried updating the 2.12.yml file myself, by looking at the updated version numbers from running "conda install" on the missing package versions, but I eventually failed to fix all of the problems.   I hope my shell history below gives some perspective to the frustration people may experience when they are not expert conda users.   I can still not get uvcdat installed, by the way.  

```
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
CONDA_LOCATION="$HOME/miniconda"
sh Miniconda2-latest-Linux-x86_64.sh -b -p $CONDA_LOCATION

wget https://raw.githubusercontent.com/UV-CDAT/uvcdat/master/conda/2.12.yml

 conda env create -f 2.12.yml
Fetching package metadata ...............

ResolvePackageNotFound: 
  - libnetcdf 4.4.1.1 5

[vagrant@localhost ~]$ conda install libnetcdf=4.4.1.1 -c conda-forge -c uvcdat
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/vagrant/miniconda:

The following NEW packages will be INSTALLED:

    curl:        7.55.1-0              conda-forge
    hdf4:        4.2.13-0              conda-forge
    hdf5:        1.10.1-1              conda-forge
    jpeg:        9b-2                  conda-forge
    krb5:        1.14.2-0              conda-forge
    libgfortran: 3.0.0-1                          
    libnetcdf:   **4.4.1.1-10**            conda-forge
    libssh2:     1.8.0-2               conda-forge

```

In the above example, I discovered that conda-forge has version 10 of libnetcdf 4.4.1.1, so I changed the *.yml file and tried again: 
```
 conda env create -f 2.12.yml
Fetching package metadata ...............

ResolvePackageNotFound: 
  - udunits2 2.2.23 0

 conda install udunits2=2.2.23 -c conda-forge -c uvcdat
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/vagrant/miniconda:

The following NEW packages will be INSTALLED:

    expat:    2.2.1-0  conda-forge
    udunits2: **2.2.23-1** conda-forge
```

So then I updated the *.yml file to use version 1 of udunits2 v2.2.23.

But then I got stuck here: 

```

 conda env create -f 2.12.yml
Fetching package metadata ...............

ResolvePackageNotFound: 
  - acme_diags v0.1b hf894526_0

[vagrant@localhost ~]$ conda install acme_diags=v0.1b -c hf894526_0 -c uvcdat
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/hf894526_0

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
...........

PackageNotFoundError: Packages missing in current channels:
            
  - acme_diags v0.1b*

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/hf894526_0/linux-64
  - https://conda.anaconda.org/hf894526_0/noarch
  - https://conda.anaconda.org/uvcdat/linux-64
  - https://conda.anaconda.org/uvcdat/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
            
```

By the way, my eventual goal is to get the ESG Publisher running.   The pre-conda installs of uvcdat used to include the necessary ESGF Data Note components for allowing the ESG Publisher to run successfully.   

Is this still true for version 2.12 of UVCDAT?

Thanks for any help....

**Comment by stefraynaud** [comment]
For udunits and netcdf, installation is possible by removing the their build number in the yml file string after the last =).
As for the acme_diags, you resolve it for instance by adding "doutriaux1" to the list of  channels in the yml file :)

However, we even should not have to use a special environment file to install cdat.

**Comment by bonnland** [comment]
Thank you for your help; I can confirm that uvcdat installs on a plain CentOS 7.4 box with the three changes you specified.   The changed lines are: 

```
channels:
- conda-forge
- uvcdat
- doutriaux1
- defaults

dependencies:

- libnetcdf=4.4.1.1

- udunits2=2.2.23
```

Thanks again for your help; it is very appreciated!

**Comment by simossk** [comment]
please help me. i tested all installation method but i get the same error.:')
Traceback (most recent call last):
  File "/home/mkoussaimi/anaconda3/envs/uvcdat/vistrails/vistrails/uvcdat.py", line 89, in <module>
    v = gui.application.start_application()
  File "/home/mkoussaimi/anaconda3/envs/uvcdat/vistrails/vistrails/gui/application.py", line 703, in start_application
    x = VistrailsApplication.init(optionsDict)
  File "/home/mkoussaimi/anaconda3/envs/uvcdat/vistrails/vistrails/gui/application.py", line 160, in init
    self.createWindows()
  File "/home/mkoussaimi/anaconda3/envs/uvcdat/vistrails/vistrails/gui/application.py", line 548, in createWindows
    from gui.uvcdat.mainwindow import UVCDATMainWindow
  File "/home/mkoussaimi/anaconda3/envs/uvcdat/vistrails/vistrails/gui/uvcdat/mainwindow.py", line 18, in <module>
    import cdms2
  File "/home/mkoussaimi/anaconda3/envs/uvcdat/lib/python2.7/site-packages/cdms2/__init__.py", line 6, in <module>
    cdat_info.pingPCMDIdb("cdat", "cdms2")  # noqa
  File "/home/mkoussaimi/anaconda3/envs/uvcdat/lib/python2.7/site-packages/cdat_info/cdat_info.py", line 205, in pingPCMDIdb
    askAnonymous(val)
  File "/home/mkoussaimi/anaconda3/envs/uvcdat/lib/python2.7/site-packages/cdat_info/cdat_info.py", line 164, in askAnonymous
    "(you can also set the environment variable UVCDAT_ANONYMOUS_LOG to yes or no)? [yes]/no: ")
KeyboardInterrupt.

**Comment by doutriaux1** [comment]
try remove ther `.uvcdat` directory in your home directory thentun `python -c "import cdms2"` and answer `yes`

**Comment by simossk** [comment]
thank you very much.
