### ISSUE TITLE
system picks up wrong pip when building ipython and tornado 

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#269]
73%] Performing install step for 'IPYTHON'
CMake Error at /Users/aashish/tools/uvcdat/build/IPYTHON-prefix/src/IPYTHON-stamp/IPYTHON-install.cmake:56 (message):
  CTEST_FULL_OUTPUT

   Command failed: 2
   'env' 'DYLD_LIBRARY_PATH=/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11:/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11:/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11:/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11:/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11:/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11:/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11:/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11:/Users/aashish/tools/uvcdat/install/lib:/Users/aashish/tools/uvcdat/install/Externals/lib:/Users/aashish/tools/uvcdat/install/Externals/lib/paraview-3.11: -bind_at_load -mmacosx-version-min=10.8 -bind_at_load -mmacosx-version-min=10.8 -bind_at_load -mmacosx-version-min=10.8 -bind_at_load -mmacosx-version-min=10.8 -bind_at_load -mmacosx-version-min=10.8 -bind_at_load -mmacosx-version-min=10.8 -bind_at_load -mmacosx-version-min=10.8 -bind_at_load -mmacosx-version-min=10.8 -bind_at_load -mmacosx-version-min=10.8' '/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/bin/pip' 'install' 'ipython==0.13'
   From /Users/aashish/tools/uvcdat/build/IPYTHON-prefix/src/IPYTHON-stamp/IPYTHON-install-out.log

  -------------------------------------------------

  Downloading/unpacking ipython==0.13

    Running setup.py egg_info for package ipython
      running egg_info
      
      warning: no files found matching 'setup2.py'
      warning: no files found matching 'setup3.py'
      no previously-included directories found matching 'IPython/deathrow'
      no previously-included directories found matching 'IPython/external/js'
      no previously-included directories found matching 'IPython/frontend/html/notebook/static/mathjax'
      warning: no files found matching 'IPython/.git_commit_info.ini'
      warning: no previously-included files found matching 'docs/#*'
      warning: no previously-included files found matching 'docs/man/*.1.gz'
      no previously-included directories found matching 'docs/attic'
      no previously-included directories found matching 'docs/build'
      no previously-included directories found matching 'docs/gh-pages'
      no previously-included directories found matching 'docs/dist'
      warning: no previously-included files matching '*~' found anywhere in distribution
      warning: no previously-included files matching '*.flc' found anywhere in distribution
      warning: no previously-included files matching '*.pyo' found anywhere in distribution
      warning: no previously-included files matching '.dircopy.log' found anywhere in distribution

  Installing collected packages: ipython

    Found existing installation: ipython 0.13.1
      Uninstalling ipython:

  Exception:

  Traceback (most recent call last):

    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/basecommand.py", line 139, in main
      status = self.run(options, args)
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py", line 271, in run
      requirement_set.install(install_options, global_options, root=options.root_path)
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1181, in install
      requirement.uninstall(auto_confirm=True)
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 495, in uninstall
      paths_to_remove.remove(auto_confirm)
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1518, in remove
      renames(path, new_path)
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/util.py", line 293, in renames
      shutil.move(old, new)
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
      rmtree(src)
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
      onerror(os.remove, fullname, sys.exc_info())
    File "/Users/aashish/tools/uvcdat/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
      os.remove(fullname)

  OSError: [Errno 13] Permission denied:
  '/Library/Python/2.7/site-packages/ipython-0.13.1-py2.7.egg/EGG-INFO/dependency_links.txt'

  

  Storing complete log in /Users/aashish/.pip/pip.log

  -------------------------------------------------

   From /Users/aashish/tools/uvcdat/build/IPYTHON-prefix/src/IPYTHON-stamp/IPYTHON-install-err.log

  -------------------------------------------------

  -------------------------------------------------

make[2]: *** [IPYTHON-prefix/src/IPYTHON-stamp/IPYTHON-install] Error 1
make[1]: *** [CMakeFiles/IPYTHON.dir/all] Error 2
make: *** [all] Error 2

**Comment by doutriaux1** [comment]
@aashish24 still true?
