### ISSUE TITLE
genutil.area_weights doesn't work with non-cartesian grids (most CMIP5 ocean grids)

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#402]
This example outlines the issue:

``` python
import cdms2 as cdm
import genutil as gutil
infile = '/work/cmip5/historical/ocn/mo/thetao/cmip5.ACCESS1-0.historical.r1i1p1.mo.ocn.Omon.thetao.ver-1.latestX.xml'
f_h = cdm.open(infile)
mask = f_h('thetao',time=slice(0,1),lev=slice(0,1))(squeeze=1)
ocean_area_frac = gutil.area_weights(mask)

>>> ocean_area_frac = gutil.area_weights(mask)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/uvcdat/latest/lib/python2.7/site-packages/genutil/averager.py", line 188, in area_weights
    wt = __myGetAxisWeights(ds, 0, axisoptions)
  File "/usr/local/uvcdat/latest/lib/python2.7/site-packages/genutil/averager.py", line 54, in __myGetAxisWeights
    raise AveragerError, 'Bounds not available to compute weights for dimension: '+ax.id
genutil.averager.AveragerError: ('B', 'o', 'u', 'n', 'd', 's', ' ', 'n', 'o', 't', ' ', 'a', 'v', 'a', 'i', 'l', 'a', 'b', 'l', 'e', ' ', 't', 'o', ' ', 'c', 'o', 'm', 'p', 'u', 't', 'e', ' ', 'w', 'e', 'i', 'g', 'h', 't', 's', ' ', 'f', 'o', 'r', ' ', 'd', 'i', 'm', 'e', 'n', 's', 'i', 'o', 'n', ':', ' ', 'j')
```

**Comment by durack1** [comment]
@doutriaux1 another 2.3 candidate..

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 just pinging you both on this..

**Comment by dnadeau4** [comment]
@durack1 Can you check issue_402 and tell me if it works for you?  I added ESMF  for non uniform grids as you suggest.

**Comment by durack1** [comment]
@dnadeau4 sure, will do this week.. What have you changed in the branch?

**Comment by dnadeau4** [comment]
I actually added your code to call ESMF regridder in the averager and return the srcAreas weight when the grid is non uniform.  No use of Numpy for non uniform grid.   

The branch is called issue_402.

+        diag = {'srcAreaFractions':None, 'srcAreas':None, 'dstAreas':None} ; # Create dictionary, with additional keys for function to return
+        dummy=ds.regrid(ds.getGrid(),regridTool='esmf',regridMethod='conserve',diag=diag)
+        wt = numpy.array(diag.get('srcAreas'))

         return cdms2.createVariable(numpy.ma.masked_array(wt, numpy.ma.getmask(ds)), axes=ds.getAxisList())

**Comment by durack1** [comment]
@dnadeau4 ok, so changes are in `genutil` and specifically the `area_weights` function as outlined [above](https://github.com/UV-CDAT/uvcdat/issues/402#issue-27364373)?

**Comment by durack1** [comment]
@dnadeau4 ok so it seems to work and output reasonable fields - though I agree with you, we need to return `srcAreaFractions` rather than the current `srcArea` ESMF output:
```python
[durack1@oceanonly ~]$ ipython
Python 2.7.10 (default, Sep 16 2015, 12:49:34)
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import cdms2 as cdm
In [2]: import genutil as gutil
In [3]: infile = '/work/cmip5/historical/ocn/mo/thetao/cmip5.ACCESS1-0.historical.r1i1p1.mo.ocn.Omon.thetao.ver-1.latestX.xml'
In [4]: f_h = cdm.open(infile)
In [5]: mask = f_h('thetao',time=slice(0,1),lev=slice(0,1))(squeeze=1)
In [6]: ocean_area_frac = gutil.area_weights(mask)
/export/durack1/built/lib/python2.7/site-packages/ESMP/src/ESMP_API.py:1241: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (srcMaskValues != None):
/export/durack1/built/lib/python2.7/site-packages/ESMP/src/ESMP_API.py:1248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (dstMaskValues != None):
In [7]: import vcs
In [8]: x = vcs.init()
In [9]: x.plot(ocean_area_frac)
Out[9]: <vcs.displayplot.Dp at 0x7f3bca331750>
```
![issue_402_output](https://cloud.githubusercontent.com/assets/3229632/9948364/34a3c2ba-5d57-11e5-99a8-e0c08d7916c3.png)

I think we need to go one further, and tweak the output field to include bounds so the `genutil.averager` function can then also work.. Currently, it's not:
```python
In [13]: ocean_area_frac.shape
Out[13]: (300, 360)
In [14]: gutil.averager(ocean_area_frac,axis=0)
---------------------------------------------------------------------------
AveragerError                             Traceback (most recent call last)
<ipython-input-14-cd98dcb1f59e> in <module>()
----> 1 gutil.averager(ocean_area_frac,axis=0)

/export/durack1/built/lib/python2.7/site-packages/genutil/averager.pyc in averager(V, axis, weights, action, returned, weight, combinewts)
   1079     if __DEBUG__: print 'Checking weights= options:',weights
   1080     #
-> 1081     filled_wtoptions = __check_weightoptions(V, axis, weights)
   1082     if __DEBUG__: print 'The weights options are ', filled_wtoptions
   1083     #

/export/durack1/built/lib/python2.7/site-packages/genutil/averager.pyc in __check_weightoptions(x, axisoptions, weightoptions)
    354             #
    355             if __DEBUG__: print 'I have only 1 axis and 1 option'
--> 356             weightoptions = __check_each_weight_option(x, axislist[0], axisindex[0], weightoptions)
    357         else:
    358             #

/export/durack1/built/lib/python2.7/site-packages/genutil/averager.pyc in __check_each_weight_option(x, ax, index, wtopt)
    288             # NOTE: THIS FUNCTION CAN BE CHANGED WHEN BOB PUTS THE FUNCTION getAxisWeights() INTO cdms2
    289             if __DEBUG__: print 'GENERATE weights specified'
--> 290             wtopt = __myGetAxisWeights(x, index)
    291             if __DEBUG__: print wtopt
    292         else:

/export/durack1/built/lib/python2.7/site-packages/genutil/averager.pyc in __myGetAxisWeights(x, i, axisoptions)
     52                     axis_wts=numpy.ones(x.getAxis(i)[:].shape)
     53             else:
---> 54                 raise AveragerError, 'Bounds not available to compute weights for dimension: '+ax.id
     55         else:
     56             axis_wts =  abs(axis_bounds[..., 1] - axis_bounds[..., 0])

AveragerError: ('B', 'o', 'u', 'n', 'd', 's', ' ', 'n', 'o', 't', ' ', 'a', 'v', 'a', 'i', 'l', 'a', 'b', 'l', 'e', ' ', 't', 'o', ' ', 'c', 'o', 'm', 'p', 'u', 't', 'e', ' ', 'w', 'e', 'i', 'g', 'h', 't', 's', ' ', 'f', 'o', 'r', ' ', 'd', 'i', 'm', 'e', 'n', 's', 'i', 'o', 'n', ':', ' ', 'j')
```

It'd also be nice to clean up the `error messages` too..

@doutriaux1 what are your thoughts on this?
