### ISSUE TITLE
UnboundLocalError in uvcdat_cdms/pipeline_helper.py

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#526]
Introduced by [vistrails:da821a](https://github.com/VisTrails/VisTrails/commit/da821a): 'action' can be undefined when passed to update_templates():
```python
    def configure_done(self):  # 1121
...
        if (...  # 1164
            action = self.update_pipeline(None, function_updates)  # 1171

        action = self.update_templates(action)  # 1173
...
```
Error I got:
```
Traceback (most recent call last):
  File "/home/vagrant/uvcdat/build-uvcdat/install/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1312, in save_triggered
    self.configure_done()
  File "/home/vagrant/uvcdat/build-uvcdat/install/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 1173, in configure_done
    action = self.update_templates(action)
UnboundLocalError: local variable 'action' referenced before assignment
```

**Comment by doutriaux1** [comment]
@remram44 do we still need this, tried to merge it back into uvcdat-master but got a zillion merge conflicts

**Comment by remram44** [comment]
Yes, this is still needed. There is no conflict.

**Comment by doutriaux1** [comment]
well github doesn't aggree:
```
We’re showing branches in this repository, but you can also compare across forks.

base: master  ... compare: uvcdat-522-fix-cdms-configure_done 
From here you can compare, discuss, and merge two points in history. You can even compare tag names and commits.

There isn't anything to compare.

We couldn't figure out how to compare these references, do they point to valid commits?

```

**Comment by remram44** [comment]
[uvcdat-master...uvcdat-522-fix-cdms-configure_done](https://github.com/UV-CDAT/VisTrails/compare/UV-CDAT:uvcdat-master...uvcdat-522-fix-cdms-configure_done)
