### ISSUE TITLE
animation seg fault on Linux

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#615]
------ Loaded plot Histogram, varnum = 1 ------ 
None None
CDMSVariable init
CDMSVariable init
stack_trace=Traceback+%28most+recent+call+last%29%3A%0A++File+%22%2Fusr%2Flocal%2Fuvcdat%2F2014-09-08%2Flib%2Fpython2.7%2Fsite-packages%2Fvcs%2FVTKPlots.py%22%2C+line+171%2C+in+configureEvent%0A++++self.scaleLogo%28%29%0A++File+%22%2Fusr%2Flocal%2Fuvcdat%2F2014-09-08%2Flib%2Fpython2.7%2Fsite-packages%2Fvcs%2FVTKPlots.py%22%2C+line+956%2C+in+scaleLogo%0A++++pw+%3D+%28W-nw%29%2FW%0AZeroDivisionError%3A+float+division+by+zero%0A&description=ZeroDivisionError%3A+float+division+by+zero&source=UV-CDAT&hashed_hostname=e3a9beb20f9cc42ce7deae544dda5d8168f5bd65&comments=&platform_version=2.6.32-431.23.3.el6.x86_64&platform=Linux&hashed_username=66dd7b1c3f39b1b15ca2abdc41ba6428046f77b1&source_version=1.2.1&severity=FATAL
http://uvcdat.llnl.gov/UVCDATUsage/log/add/error/
Traceback (most recent call last):
  File "/usr/local/uvcdat/2014-09-08/vistrails/vistrails/gui/uvcdat/reportErrorDialog.py", line 87, in sendError
    urlencode(data))
  File "/usr/local/uvcdat/2014-09-08/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/uvcdat/2014-09-08/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/local/uvcdat/2014-09-08/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/uvcdat/2014-09-08/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/local/uvcdat/2014-09-08/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/uvcdat/2014-09-08/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
/usr/local/uvcdat/2014-09-08/lib/python2.7/site-packages/vcs/Canvas.py:3494: UserWarning: Unrecognized vcs plot keyword: cdmsfile, assuming backend (vtk) keyword
  warnings.warn('Unrecognized vcs plot keyword: %s, assuming backend (%s) keyword'%(keyarg,self.backend.type))
/usr/local/uvcdat/2014-09-08/lib/python2.7/site-packages/vcs/Canvas.py:3494: UserWarning: Unrecognized vcs plot keyword: cell_coordinates, assuming backend (vtk) keyword
  warnings.warn('Unrecognized vcs plot keyword: %s, assuming backend (%s) keyword'%(keyarg,self.backend.type))
/usr/local/uvcdat/2014-09-08/lib/python2.7/site-packages/vcs/Canvas.py:3729: UserWarning: VCS Behaviour changed, in order to interact with window, start the interaction mode with:
 x.interact()
  warnings.warn("VCS Behaviour changed, in order to interact with window, start the interaction mode with:\n x.interact()")
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python2.7: xcb_io.c:273: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
/usr/local/uvcdat/2014-09-08/bin/uvcdat: line 6: 12714 Aborted                 (core dumped) python2.7 $INSTALL_PREFIX/vistrails/vistrails/uvcdat.py $@

**Comment by doutriaux1** [comment]
should be fixed by #1038
