### ISSUE TITLE
Error reporting returns 404

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#930]
URL is `http://uvcdat.llnl.gov/UVCDATUsage/log/add/error/`

```
Traceback (most recent call last):
  File "/vagrant/vistrails/gui/uvcdat/reportErrorDialog.py", line 87, in sendError
    urlencode(data))
  File "/home/vagrant/uvcdat/build-2.0.0-356-g4c51010/install/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/vagrant/uvcdat/build-2.0.0-356-g4c51010/install/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/home/vagrant/uvcdat/build-2.0.0-356-g4c51010/install/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/vagrant/uvcdat/build-2.0.0-356-g4c51010/install/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/home/vagrant/uvcdat/build-2.0.0-356-g4c51010/install/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/home/vagrant/uvcdat/build-2.0.0-356-g4c51010/install/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by doutriaux1** [comment]
@mattben we should be good to go now right?

**Comment by doutriaux1** [comment]
@remram44 can you confirm it works for you now, app is back up

**Comment by remram44** [comment]
Yes I didn't get a server error in a while.
